live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
Originally, we performed a very shallow clone of the dlpx-app-gate
repository, optimizing for latency of the build, and the size of the
resultant VM artifacts.
Not having the repository's history on our internal VM images is a
divergence from what we do for other images, and can pose a problem for
some of our internal developer tooling.
Thus, this change reverts this functionality; now we do a full clone
of the dlpx-app-gate repository, optimizing for developer productivity
and utility of the resultant VM images, rather than build latency.
=> Clone full history of dlpx-app-gate repository

README.md, live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
fio is used by the ZFS performance suites as well as the storage tests.
Also updated the README, to clarify which ansible roles are used when.
=> Add fio to the image

live-build/base/config/package-lists/tools.list.chroot, live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
This change removes the hard coded list of dependencies for the
virtualization package. The virtualization package should now contain
the list of its dependencies, so there's no reason to have a hard coded
list here. When pulling in the virtualization package, we'll pull in
that package's dependencies as well.
=> Rely on virtualization package dependencies

.travis.yml
This change modifies the .travis.yml file, in order to run the three
test scripts concurrently, rather than serially. This ensures all tests
will be run for any given build, even if one of them fails.
=> Use TravisCI's "build matrix" feature

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This is a change that we need in both dev and production.
Tested with internal-minimal.
==== Before change ====
```
delphix@appliance:~$ sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 0
delphix@appliance:~$ sysctl net.ipv4.conf.all.promote_secondaries
net.ipv4.conf.all.promote_secondaries = 1
delphix@appliance:~$ grep secondaries /etc/sysctl.conf
delphix@appliance:~$ grep disable_ipv6 /etc/sysctl.conf
```
Not sure how the promotion of secondaries is set here but I
believe that we should be explicit.
==== After change ====
```
delphix@appliance:~$ tail /etc/sysctl.conf
#
#fs.protected_hardlinks=0
#fs.protected_symlinks=0
net.ipv4.conf.all.promote_secondaries=1
net.ipv6.conf.all.disable_ipv6=1
delphix@appliance:~$ sysctl net.ipv4.conf.all.promote_secondaries …
```
=> sysctl.conf: disable IPv6 addresses and promote secondaries

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This change modifies the log level of the "systemd-networkd" service,
such that the service's log will contain more information about what
exactly it is doing. This is helpful for diagnosing problems, in the
event that networking fails.
For example, without this change, the log contains the following:
$ sudo journalctl -b -u systemd-networkd | cat
-- Logs begin at Tue 2018-05-08 23:24:05 UTC, end at Tue 2018-05-08 23:44:35 UTC. --
May 08 23:24:48 appliance.example.com systemd[1]: Starting Network Service...
May 08 23:24:48 appliance.example.com systemd-networkd[1068]: Enumeration completed
May 08 23:24:48 appliance.example.com systemd[1]: Started Network Service.
May 08 23:24:48 appliance.example.com systemd-networkd[1068]: lo: Link is not managed by us
May 08 23:24:48 …
=> Set log level to "debug" for systemd-networkd

live-build/misc/ansible-roles/appliance-build.minimal-internal/tasks/main.yml
Now that we're using the cloud-init EC2 datasource for our internal VM
artifacts, this adds roughly 100 seconds of additional latency to our
boot time (i.e. the time until ssh is available) for VMs not running in
EC2. This is because the default timeout is 50 seconds, and cloud-init
will attempt to contact 2 endpoints, waiting 50 seconds for each.
This change reduces this timeout to 10 seconds, reducing the total
additional boot time latency to roughly 20 seconds (when not running in
EC2). Further, the max_wait time was reduced to 24 seconds, to maintain
the same ratio of timeout to max_wait time as before (the default
max_wait is 120).
=> Reduce time spent waiting for EC2 datasource

live-build/misc/ansible-roles/appliance-build.masking-development/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
In [this Jenkins job](http://selfservice.jenkins.delphix.com/job/dlpx-app-gate/job/master/job/integration-tests/job/post-push/job/dlpxdc.co/job/split-precommit-dxos/865/consoleFull), an old version of the code was tested. The job should have run against `28cd2478f71` (LX-978 Disable flaky tests in MetadataServiceTest on Linux), but instead it ran against `d59513a1f5b` (LX-142 Fix phonehome on Linux).
Our Jenkins jobs fetch a specific refspec in order to reduce the amount of time it takes to clone the repository:
```
> git fetch --no-tags --progress https://gitlab.delphix.com/app/dlpx-app-gate.git +refs/heads/projects/dx4linux:refs/remotes/origin/projects/dx4linux # timeout=60
```
The Ansible roles that clone product repositories create a local branch named `projects/dx4linux`. When a …
=> Clone master branch of product repositories

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This commit adds the delphix user to the root group as a matter of convenience. The delphix management service runs as root with root:root owned log files that are group readable. This minimally allows the delphix user to be able to read those log files without having to use sudo.
I tested this by building an internal-minimal image, booting it with qemu and verifying that the configuration was correct:
```
delphix@appliance:~$ id
uid=1000(delphix) gid=50(staff) groups=50(staff),0(root)
```
Closes #11 add the delphix user to the root group
=> Add the delphix user to the root group

live-build/misc/ansible-roles/appliance-build.install-delphix-zfs-packages/tasks/main.yml
By default, when building linux kernel modules, the compiler is pretty
aggressive when inlining functions, which can make it more difficult to
observe and debug a running system. In the interest of being able to
better debug production systems, this change modifies the configure flags
used when building the SPL and ZFS repositories.
By enabling the "--enable-debuginfo" configure flag, the two repositories
will be compiled using the "-fno-inline" compiler flag, which will make
stack traces and tools that leverage function boundary kprobes more
useful.
=> Use "--enable-debuginfo" when building SPL and ZFS

bors.toml
This change will instruct bors to verify that the CLA has been signed,
prior to allowing a pull request to be merged.
=> Add CLA check to bors configuration

live-build/base/config/package-lists/tools.list.chroot, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
new tools:
```
$ dig google.com
; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14310
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.			IN	A
;; ANSWER SECTION:
google.com.		213	IN	A	216.58.194.206
;; Query time: 22 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Wed May 30 17:39:39 UTC 2018
;; MSG SIZE  rcvd: 55
$ nslookup google.com
Server:		10.0.2.3
Address:	10.0.2.3#53
Non-authoritative answer:
Name:	google.com
Address: 216.58.194.206
Name:	google.com
Address: 2607:f8b0:4005:805::200e
```
Without debug info:
```
...
-- Reboot --
May 30 16:38:32 appliance systemd[1]: Starting …
```
=> DNS debugging tools and logs

live-build/misc/ansible-roles/appliance-build.install-delphix-zfs-packages/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
As SPL has been merged into the ZFS repo, we now only need to `make install` inside ZFS. No other changes are required.
**Testing**
Ran appliance-build: http://collins.d.delphix.com:32423/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/post-push/2/console
Loaded the bits in qemu on a `bootstrap-18-04` dcoa system and verified that it still boots and that basic ZFS commands work. I've also verified that the image is indeed running the bits from https://github.com/delphix/zfs/pull/8 by temporarily modifying the ZFS repo in `appliance-build.zfsonlinux-development/tasks/main.yml`
=> SPL has been merged into ZFS

live-build/misc/live-build-hooks/92-ova-machine-image.binary
We often run into OOM issues with our current OVA configuration when
running our automated integration tests. This change is an attempt to
alleviate that issue, by increasing the amount of memory allocated to
the OVA, from 7GB to 8GB (~15% increase).
=> Bump RAM size for OVA from 7GB to 8GB

live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
On Illumos, we explicitly created our own `rsync` `smf` service and used an `rsync` binary checked into the app-gate repository. However, we don't appear to be doing any real customization to `rsync` so I thought it would be cleaner to just use the existing Ubuntu `rsync` binary and `systemd` service rather than replacing them with effectively identical versions.
The default `rsync.service` is already wanted by `multi-user`, and it the only thing it's missing to start up is the config file. I added the `port` specification in the config file because, even though 873 is the default value, I wanted to make it clear where it's specified - similar to what we do on Illumos in `delphix_rsync.xml`.
One thing to note is that linux's `rsync.service` file passes `--no-detach` when invoking `rsync` …
=> LX-151 rsync service

scripts/run-live-build.sh
The masking packages are now built from master rather than the project branch, so fetch them from there instead.
I didn't test this but verified that [this job](http://ops.jenkins.delphix.com/job/dms-core-gate/job/master/job/build-package/job/post-push/1/consoleFull) was in fact publishing to the `master` prefix:
```
10:55:36 [distributions] Running shell script
10:55:37 + aws s3 sync --delete --only-show-errors . s3://snapshot-de-images/builds/jenkins-ops/dms-core-gate/master/build-package/post-push/1
[Pipeline] writeFile
[Pipeline] sh
10:55:46 [distributions] Running shell script
10:55:46 + aws s3 cp latest s3://snapshot-de-images/builds/jenkins-ops/dms-core-gate/master/build-package/post-push/latest
10:55:46 Completed 65 Bytes/65 Bytes (599 Bytes/s) with 1 file(s) remaining
upload: …
```
=> Fetch masking packages from master prefix

live-build/base/config/package-lists/minimal.list.chroot, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
Install the `auditd` package as part of the _minimal-common_ ansible role. Update the `/etc/audit/` config parameters for log rotation and add rules for recording all commands that are executed (i.e. via execve).
**Testing**
Booted  the build artifacts with QEMU and verified in the console that `auditd` was installed and that the config files were updated as expected.  Also used `ausearch(8)` and `aureport(8)` tools to confirm that command auditing is occurring.
=> LX-1039 enable auditd on linux

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
When testing OOM conditions in the stack, it was discovered that the
script which creates the hprof dump could fail to be run because the JVM
uses fork(2) rather than vfork(2). In order to allow the dump creation
to proceed, the default settings for vm.overcommit_memory needed to
change from the default.
Additionally, this change enables application core dumps for all users
and creates a common directory in which all cores are written. Cores
will use the same filename pattern as on illumos.
Tested that an hprof dump is successfully created when the stack
encounters an OOM error using the fixed test_out_of_memory blackbox
test.
Created a live build, and tested that cores are created for root and
user processes in the correct location.
=> LX-1100 appliance-build portion of LX-788

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml, live-build/misc/live-build-hooks/90-raw-disk-image.binary
This patch adds a swap device to the engine early in the build process. We create the zvol with appropriate configuration and add it to the new machine's /etc/fstab file. In order to format the device, the /dev/zvol pseudo-device needs to exist. However, that device only exists if the bootstrap machine (not the docker container) has the zfsutils package installed. To solve this, an ansible playbook and task were added, which should be executed by the automation to install the package.  Finally, when we've finished the build we have to stop the zed service in order to unload the zfs kernel modules.
=> LX-1098 Add swap device to engine

live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
libelf-dev is a new dependency for building kernel modules. Note that it doesn't fail the build, but generates warnings.
{noformat}
18:11:39 /usr/bin/make -C /usr/src/linux-headers-4.15.0-23-generic SUBDIRS=`pwd`  CONFIG_DEBUG_INFO=y CONFIG_ZFS=m modules
18:11:39 make[2]: Entering directory '/usr/src/linux-headers-4.15.0-23-generic'
18:11:40 Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
{noformat}
This change removes those warnings from git-zfs-make. Similar changes are done in the zfs-package-build job in LX-1106.
=> Building zfs kernel modules requires libelf-dev

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
When testing locally, the docker image will be generated the first time `ansible-playbook bootstrap/playbook.yml` is run. When the Dockerfile is changed, we want to be able to re-run `ansible-playbook bootstrap/playbook.yml` to rebuild the image. Unfortunately the `docker_image` ansible plugin only looks if the docker image with a given name exists, and won't rebuild it. We add a flag to rebuild it every time.
**Testing**
Tested by running `ansible-playbook bootstrap/playbook.yml` locally.
=> Docker image not rebuilt when testing locally even if Dockerfile changed

README.md, bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
This change adds the "qemu" package installation into the ansible role
for the bootstrap system. As a result, we can remove the commands from
the README.md that instruct the user to explicitly install this package.
=> Add "qemu" package to bootstrap ansible role

live-build/misc/live-build-hooks/90-raw-disk-image.binary
This retry loop will help is handle the case where the `/dev/zvol` device takes a few seconds to be created. It will delay for a maximum of 20 seconds, and will exit if the device doesn't appear.
=> LX-1108 swap zvol formatting sometimes fails

Makefile, docker/Dockerfile, live-build/misc/live-build-hooks/92-ova-machine-image.binary
I've adapted the Makefile's find commands to also work properly under OSX.
We can now run all the checks locally by executing `make checks` without needing a docker container
The prerequisites on OSX is to install shellcheck, shfmt and ansible-lint. This can be done easily with brew:
```
brew install shellcheck shfmt ansible-lint
```
Note that I've also added a small change to `92-ova-machine-image.binary` to make shfmt pass.
**Testing**
I've tested `make checks` on OSX and tested `./scripts/docker-run.sh make checks` on Linux.
I've also confirmed that the format change in `92-ova-machine-image.binary` doesn't affect the contents of the "$OVA_DIRECTORY/$APPLIANCE_VARIANT.mf" file created.
=> Allow checking format of scripts locally with: "make checks"

Makefile
All of our current make targets are actually "phony targets", since
they're not intended to result in a file of that same target name. See
also: https://www.gnu.org/software/make/manual/make.html#Phony-Targets
This is a simple change to list all of our make targets as ".PHONY".
=> Label make targets as .PHONY

live-build/misc/ansible-roles/appliance-build.install-delphix-s3-packages/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.install-delphix-zfs-packages/meta/main.yml, live-build/misc/ansible-roles/appliance-build.masking-common/meta/main.yml, live-build/misc/ansible-roles/appliance-build.virtualization-common/meta/main.yml, scripts/docker-run.sh, scripts/run-live-build.sh
Right now, we cannot specify different buckets for the various delphix components fetched from s3. 
This change simplifies what is being passed down to live-build: instead of having separate prefix and bucket components, we pass the s3 url directly.
Note that the jenkins job can still pass us a prefix instead of a full URL, so we make sure that we can still handle that case.
Custom ZFS s3 URL: http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/60/parameters/ (pass)
git-ab-pre-push: http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/59/ (pass)
=> Allow specifying different buckets and prefixes for each s3 component

live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
Since landing the changes for LX-148 to the dlpx-app-gate repository, we
can remove some logic from the "virtualization-common" Ansible role;
this configuration has been moved into the dlpx-app-gate repository.
Additionally, the "delphix-virtualization" package now contains a post
installation script do any service manipulation that's required, so we
no longer need to do that here, either.
=> Update Ansible role to account for LX-148

scripts/build-ancillary-repository.sh
Trunk has been already updated to version 171.
We need this to merge with trunk.
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/87/ (passed)
=> Upgrade to Java 8 update 171

live-build/base/config/package-lists/minimal.list.chroot, live-build/base/config/package-lists/tools.list.chroot, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This adds and configures `kdump` so that we can get crash dumps, and adds `crash` so that we can examine them.
Note that this adds some time to the build, because downloading debug kernel from the Ubuntu repository for debug packages is quite slow (it takes ~15min to download <600MB). Once we start mirroring all of the upstream Ubuntu packages, this should no longer be an issue.
This change requires expanding the size of the disk on the bootstrap vm, which is blocked until the fix for DOAM-786 is deployed. However, I've tested building a single variant, and used qemu to verify that crash dumps are gathered successfully. I'll run `git-ab-pre-push` after the bootstrap golden image is updated.
=> LX-960 Enable kernel crash dump support

scripts/build-ancillary-repository.sh
Pending [TOOL-5988](http://reviews.delphix.com/r/41802/) and [TOOL-5989](http://reviews.delphix.com/r/41803/). I won't push this until I verify that packages are available in S3 with the new prefix.
=> The virtualization packages are now built from master rather than the project branch, so fetch them from there instead.

scripts/docker-run.sh
When running the docker container via the TravisCI automation, we're
seeing the following error:
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/docker/containers/cf46734cb251f78e84b33e1ce222dbfda6f59b73f102ea0f2a072b327cb3e1af/shm\\\" to rootfs \\\"/var/lib/docker/overlay2/88fa4f0902de66da3647b57c9f5027ec13c4ed8f9a02e4217e39e5b59195119b/merged\\\" at \\\"/dev/shm\\\" caused \\\"evalSymlinksInScope: too many links in /var/lib/docker/overlay2/88fa4f0902de66da3647b57c9f5027ec13c4ed8f9a02e4217e39e5b59195119b/merged/dev/shm\\\"\"".
This change attempts to workaround this problem, by explicitly
specifying the "--ipc none" option to "docker …
=> Use "--ipc none" with "docker run"

live-build/base/config/package-lists/minimal.list.chroot
"You really, really want to run rngd" – H. Peter Anvin, Linux x86
architecture maintainer, quoted in "LCE: Don't play dice with random
numbers" (https://lwn.net/Articles/525459/)
/dev/random in Linux doesn't take advantage of Intel/AMD hardware RNGs,
leading to entropy exhaustion on EC2 VMs when applications do lots of
reads from /dev/random. In particular, the Oracle JDBC driver is one
such application. So is the Delphix Virtualization application, which
reads /dev/random at startup to create some key. When there isn't enough
entropy, these reads just hang.
The solution is to install the rng-tools package, which sets up the
rngd(8) daemon. This monitors the hardware RNGs and supplies data from
them to the kernel’s entropy pool.
Co-authored-by: Basil Crow <basil.crow@delphix.com>
=> Appliance does not take advantage of hardware RNGs

live-build/misc/ansible-roles/appliance-build.minimal-common/handlers/main.yml, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
Assertion failures in zfs call `spl_panic`, which by default does not trigger a kernel panic. This change sets the `spl_panic_halt` parameter for the `spl` module so that we will get a kernel panic, and therefore a crash dump, on zfs assertion failures.
=> LX-1194 ZFS panics should result in kernel panics

live-build/misc/live-build-hooks/81-upgrade-repository.binary
We have a few failures lately, such as:
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/119/console
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/120/console
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/123/console
It could be caused by a failure to update the packages list before running apt-download, or it could be issues with the Ubuntu repository. In any case, `apt update` would be a good thing to have there.
pre-push: http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/23/console (passed)
=> Should run apt update before fetching packages

live-build/misc/live-build-hooks/81-upgrade-repository.binary
This is intended to solve the case where the version of ZFS modules
installed does not match the version of the kernel that comes with
the package 'linux-generic', resulting in a broken appliance.
Pre-commit:
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/26 (pass)
build with a different zfs kernel modules version (should fail):
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/121/console (fail as expected)
Fixes #73
=> Fail build when 2 kernel versions are detected

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
We need to enable PAM "conversations" -- the ability of PAM modules to display errors to the user (e.g. the user is locked out message) and soon also our own CRA interaction. Conversations in `sshd` are enabled via the `ChallengeResponseAuthentication` setting. Currently, `sshd_config` it disabled.
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/42/flowGraphTable/
=> LX-194 pam module for linux - phase I (enable PAM module conversations)

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
The appliance should panic and generate a crash dump when it receives an NMI, to allow debugging of engines which are in some bad state such that interactive debugging isn't possible.
=> LX-1217 Generate crash dump on NMI

live-build/base/config/package-lists/minimal.list.chroot, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This change installs the Azure Linux agent by default as a core dependency but disables its service. We'll eventually want to re-enable the service for Azure VMs, though probably with reduced functionality (configured in `/etc/waagent.conf`). I decided to do this much now because we need the azure specific udev rules that come in this package and we'll need want the agent at some point as well. 
I tested this by running through the live build process and using qemu to check that the image booted properly, had the new udev rules and that `walinuxagent.service` was present but disabled.
=> LX-1213 Install azure udev rules

live-build/misc/ansible-roles/appliance-build.qa-internal/handlers/main.yml, live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
Completed steps 1-5 from https://github.com/delphix/appliance-build/blob/master/README.md
Logged into the VM and checked for the existence of nftables, plus ensured the default ruleset was flushed:
```
delphix@ip-10-110-202-152:~$ sudo nft list ruleset -a
delphix@ip-10-110-202-152:~$ cat /etc/nftables.conf 
#!/usr/sbin/nft -f
flush ruleset
```
=> LX-1179 QA needs nftables installed on Linux DEs

live-build/base/config/package-lists/tools.list.chroot
This commit installs the snmp package to our base appliance image.
The SNMP client utilities included in this packge (e.g. snmpwalk and
snmpget) are useful for the field/support to debug the snmpd daemon.
Additionally, blackbox needs these utilities for test automation, so
installing this package kills two birds with one stone.
I tested this by installing the snmp package and making sure that the
snmpget and snmpwalk utilities get installed and work as expected.
=> Install snmp package containing client utilities by default.

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
The `appliance-build.bootstrap apt` task has been failing when trying to install the latest packages. Basil suspects that the issue is that it's trying to install a package which is no longer available from Ubuntu because the `apt` index is old (it’s from when the `bootstrap-18-04` group was made). 
He suggested adding these commands to update the `apt` indices before performing the install so that the latest version is always pulled in.
Testing:
I ran `ansible-playbook bootstrap/playbook.yml` without the changes and saw the same failures we've been seeing in the Jenkins job. With the changes, `ansible-playbook bootstrap/playbook.yml` completes successfully.
=> bootstrap configuration should always use the latest apt index

live-build/variants/internal-dev/ansible/playbook.yml
This change modifies the internal-dev configuration to also install the "nftables" package.
The internal-dev variant should have nftables installed so that blackbox tests that use this utility can be run against the dev variant.
- Ran live-build on a bootstrap VM and verified nftables exists.
- [ab-pre-push job](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/74/console)
- Verified the resulting image boots and has nftables installed. The cloned VM: pg-ab-nftables.dlpxdc.co
=> LX-1279 internal-dev variant should have nftables installed

live-build/base/config/package-lists/tools.list.chroot, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
The snmp-mibs-downloader package downloads most common MIBs, and
includes a utility that can be used to download new MIBs. These MIBs are
used by tools such as snmpget and snmpwalk to resolve numeric OIDs to
human readable object names.
`git ab-pre-push`: http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/76/flowGraphTable/
=> Install common MIBs and enable MIB loading for SNMP client tools.

live-build/misc/ansible-roles/appliance-build.delphix-ldap/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
This companion change of LX-198 configures the CLI NSS module in virtualization appliances. This includes updates to the NSS configuration to add the new module and the NSCD configuration to prevent our module from being skipped by the `passwd` NSCD cache. For development variants, it also adds the `libnss3` development libraries.
It also takes charge of creating the `cli` user used as a placeholder of the uid 65434 assumed by all cli users. This user is no longer created by app gate code because `refresh_databases.sh` is going away (whose real purpose was to update `/etc/passwd` and `/etc/shadow` with native engine users, which we don't want to do anymore).
Finally, this change fixes a minor issue in configuring sshd and, more importantly, fixes the LDAP role which in its current form …
=> LX-198 delphix nsswitch functionality (nss and passwordless auth config)

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This change modifies the "minimal-common" Ansible role to no longer modify
the "/etc/sysctl.conf" file, but instead use the "sysctl.d" directory. This
should result in no changes to the normal operation of the appliance, but
makes upgrade more resilient as our "local" changes will not be overwritten
by the maintainer supplied "/etc/sysctl.conf" file.
=> Use "sysctl.d" for appliance customizations

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
As the comment states, we would like to use the `internal-qa` variant for pre-push testing; however, in order to do that, we would currently need to revamp our entire pre-push testing workflow. As a workaround, we temporarily include the build dependencies in the `internal-qa` variant to avoid having to revamp the pre-push testing workflow. Once the pre-push testing workflow is redone, we can move the build dependencies back into the `internal-dev` variant.
=> Temporarily install build dependencies in Virtualization Engine product variants

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
We currently install `gcc` but not `g++` and `make`. `g++` and `make` are needed to build the Virtualization Engine. Instead, this change installs `build-essential`, which includes `gcc`, `g++`, and `make`.
Testing done: Installed `build-essential` on a QA variant VM. Then successfully built the Virtualization Engine.
=> Add build-essential to the list of build dependencies for the Virtualization Engine

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
This change adds the "awscli" package to the list of virtualization
development dependencies. This makes it easier to download the upgrade
repositories that are generated via Jenkins and stored in AWS S3. These
upgrade repositories are needed for testing our upgrade logic on Linux.
=> Add "awscli" to virtualization development packages

scripts/build-ancillary-repository.sh
We must not strip debug symbols when building java since java debugging tools depend on them.
- precommit: http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/140/
- manually built the java package and verified that jstack and jmap work on java cores.
=> LX-1281 jstack can't read Java core file on Linux

scripts/build-ancillary-repository.sh
The ZFS packages are now built from master rather than the project branch, so fetch them from there instead.
=> Fetch ZFS packages from master S3 bucket

live-build/variants/internal-dev/ansible/playbook.yml
In order for LDAP to work properly, we need a specific ordering of the
values contained in the "passwd" line of the "/etc/nsswitch.conf" file.
Currently, that line looks like this:
passwd:         compat systemd delphix ldap
As a result, logging in using one's LDAP user does not work. To fix
this, we need this line to look like the following:
passwd:         compat systemd ldap delphix
Essentially, we need the "delphix" value to always be last.
Due to the way the virtualization package configures this line, we need
to ensure the virtualization package is installed after the LDAP
specific configuration has already been applied. This change acheives
this goal by changing the order in which the appliance-build ansible
roles are applied; i.e. now the LDAP specific role is applied first, and …
=> Fix LDAP for the "internal-dev" variant

live-build/misc/ansible-roles/appliance-build.delphix-ldap/files/80-internal-ldap, live-build/misc/ansible-roles/appliance-build.delphix-ldap/tasks/main.yml, live-build/variants/internal-dev/ansible/playbook.yml
This works on Illumos appliances, so developers will expect it to work
on Linux as well. Here we do something slightly better than what we do
on Illumos by restricting passwordless sudo to LDAP users, which makes
it less likely that users will overlook bugs where we accidentally rely
on these extra privileges which don't exist on the version we ship.
=> Add passwordless sudo for LDAP users on internal-dev appliances

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This change can safely land before the corresponding change to zfs, since the property will be silently ignore if it isn't valid.
=> Set tunable to enable accurate zfs send size estimates

live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
Disable the --mange-gids flag for nfs-mountd. By default, the service provides
the --manage-gids flag so NFS will be aware of group membership for users in
more than 16 groups. However, this flag has a bug, preventing users from
accessing files owned by a group they are a member of, unless it's their
primary group.
=> LX-1358 nfs-mountd --manage-gids bug prevents sybase user from provisioning Oracle VDBs

live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
This utility is needed when running `make checkstyle` in the ZFS repo.
testing: running http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/86/
=> install shellcheck

scripts/build-ancillary-repository.sh
In the "build-ancillary-repository.sh" script, we incorrectly use the
virtualization package's "latest" S3 prefix when assigning a value to
the AWS_S3_URI_PLATFORM variable.
If either the AWS_S3_URI_PLATFORM or AWS_S3_PREFIX_PLATFORM variables
are set, this won't cause a problem, but for "manual" builds that
"latest" prefix will be used (i.e. when neither of those environment
variables are set). As a result, we'll fail to download the
"delphix-platform" package (and add it to the ancillary repository),
which will result in the build failing with the error:
E: Unable to locate package delphix-platform
The fix is to simply use the proper "latest" S3 prefix for this package.
=> Fix assignment of the AWS_S3_URI_PLATFORM variable

live-build/misc/upgrade-scripts/execute, live-build/misc/upgrade-scripts/verify
The purpose of this change is to replace the use of "dist-upgrade" on
upgrade, with installing the specific new version of "delphix-entire".
This way, we're more sure of exactly what packages (and the specific
versions of those packages) we'll end up with after the upgrade.
=> Install new version of delphix-entire on upgrade

live-build/misc/live-build-hooks/82-upgrade-repository.binary, live-build/misc/live-build-hooks/template.info
Added a version.info file in the upgrade image.
`DLPX_MIN_VERSION` (same as on Illumos) is for limiting how far a customer can jump with an upgrade (right now on Illumos we have it as 2 major releases)
`DLPX_MIN_REBOOTED_VERSION` is a new field that we will use to disallow deferred upgrades for a version.  Open to any better names for this..
Testing:
1. Ran `git ab-pre-push -v internal-dev`
2. Uploaded upgrade image
3. Verified version.info contents were correct
```
delphix@dt-linux:~$ cat /var/dlpx-update/9999.0.0.0/version.info 
#
#
#
VERSION=2018.10.23.00
MINIMUM_VERSION=5.3.0.0
MINIMUM_REBOOT_REQUIRED_VERSION=5.3.0.0
```
=> LX-1539 Add version.info to Linux upgrade image

live-build/misc/ansible-roles/appliance-build.delphix-ldap/files/80-internal-ldap, live-build/misc/ansible-roles/appliance-build.masking-development/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
Our LDAP users are now members of the staff group. The files in the git
repos cloned on the internal-dev variant are already owned by the staff
group, but they need to be group writable in order to allow LDAP users
to push changes.
=> Allow building with LDAP users

live-build/misc/upgrade-scripts/upgrade-container, live-build/misc/upgrade-scripts/verify
This change adds a new "run" option to the "upgrade-container" script
which is a wrapper around the "systemd-run" command. This is meant to
make it slighly easier to run commands in a given upgrade container
during development and/or testing.
This also provides a thin layer of encapsulation between users/scripts
that need to run commands in the container, and the details of actually
doing that (e.g. we could potentially modify the implementation of this
"run" option without modifying the consumers of it).
=> Add new "run" option to "upgrade-container" script

live-build/misc/upgrade-scripts/common.sh, live-build/misc/upgrade-scripts/execute, live-build/misc/upgrade-scripts/upgrade-container, live-build/misc/upgrade-scripts/verify
This changes the interface of the upgrade scripts such that the version
being used for the upgrade or verification does not have to be specified
as an option/parameter to the script. Rather, we now infer the version
from the path of the script being executed, since all of these scripts
will reside in a version specific subdirectory of "/var/dlpx-update".
This eliminates the inconsistency between the scripts, where some would
require the version to be specified using "-v", and others would require
the version to be passed as a positional parameter.
=> Infer version from path of script being executed

live-build/misc/upgrade-scripts/common.sh, live-build/misc/upgrade-scripts/upgrade, live-build/misc/upgrade-scripts/upgrade-container, live-build/misc/upgrade-scripts/verify, live-build/misc/upgrade-scripts/verify-impl
This change adds a new "upgrade" script to the set of upgrade-scripts. This
new script is intended to be used to upgrade an existing appliance to the
version contained in the upgrade image; it script supports both,
"in-place" and "not-in-place" upgrades.
=> Add "upgrade" script that can upgrade an appliance

live-build/misc/upgrade-scripts/verify
We need to report 100 progress at the end for any scripts that is called by `UpgradeManagerImpl#runScriptWithStdoutCallback` because it treats script execution as failure if any of the following condition is true:
* non-zero exit status is received.
* 100 progress is not reported.
*  Uploaded new script to the failing VM and ran verify from the UI.
* `git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/210/)
=> DLPX-61294 Linux upgrade verify fails, trunk to trunk

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
The log processing script requires the ordereddict and junit modules.
It would be preferable to install these modules via apt as packages,
but the packages in the apt repo do not work correctly, so we install
pip and use it to install the needed modules.
Testing:
I built the qa variant and verified `pip` was available. pre-push build is
running [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/pre-push/170/console)
=> Add python-pip for zfstest log processing

live-build/base/config/archives/localhost.pref, live-build/misc/upgrade-scripts/execute, scripts/build-ancillary-repository.sh, scripts/docker-run.sh
delphix-platform will be a package generated by the linux-pkg framework.
Note that this is a breaking change, and should be pushed along with changes in other repositories.
See main review http://reviews.delphix.com/r/44644 for more details.
=> Use packages generated by linux-pkg

live-build/misc/live-build-hooks/template.ovf
This fixes the device ids and serial numbers for Linux based VMs on ESXi by providing the `disk.EnableUUID` key.
Confirmed by building a complete OVA archive using pre-push (build #266) and using that OVA to create a new VM.  The VM boots and has properly configured device UUIDs (as seen by `udevadm info`).  Also confirmed that the 'disk.EnableUUID' key was present in the VM's vmx file.
=> Enable disk.EnableUUID in the OVA Template

live-build/misc/upgrade-scripts/common.sh, live-build/misc/upgrade-scripts/upgrade-container, live-build/misc/upgrade-scripts/verify-impl
This is a reattempt of a discarded PR https://github.com/delphix/appliance-build/pull/132
Just to summarize, we discussed that adding additional binding directory and cherry-picking logs to copy was not a clean solution and should be leveraging `support_info` script if possible.
This PR uses `support_info` script to collect logs within the container and saves to `/var/dlpx-update/verify-logs` directory.
There is one TODO as noted below but just wanted to get early feedback how do you guys think about the approach.
TODO:
* I need to disable progress reporting from `support_info` script since app-gate doesn't know which ones are coming from `verify` script.
Testing
* Bundle collected at expected location
```Complete! The compressed log bundle is at …
```
=> Lx 1418 Add mechanism to save container logs to a host

live-build/misc/upgrade-scripts/upgrade, live-build/misc/upgrade-scripts/upgrade-container
We need to ensure the correct configuration is in place, prior to
executing the upgrade verification logic (i.e. prior to running
"verify-impl"). This change updates the "upgrade" script to do this.
Additionally, this only applies to "not-in-place" upgrades, since we
don't do any configuration migration for "in-place" upgrades.
=> Migrate configuration prior to running "verify-impl"

live-build/misc/upgrade-scripts/execute
The following commit broke the "execute" script:
commit e3ea5c8dc820ce276553c16ba3ba506540495337
Author: Prakash Surya <prakash.surya@delphix.com>
Date:   Thu Dec 13 10:15:40 2018 -0800
Enforce version.info requirements in upgrade scripts
As an example, running "upgrade" resulted in this error:
E: Version '' for 'delphix-entire' was not found
execute: upgrade failed; from '' to ''
upgrade: '/var/dlpx-update/2018.12.13.7/execute' failed in 'delphix.IPS0gAD'
The problem is we use the "INSTALLED_VERSION" and "VERSION" variables in
the "execute" script, but that commit removed the code that was
responsible for setting those variables. This change resolves the issue
by adding code to set these variables prior to them being used.
=> Fix recent regression in "execute" script

live-build/misc/live-build-hooks/90-linux-migration-artifact.binary, live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute, scripts/docker-run.sh
LX-1551 dx_apply for migration
LX-1553 dx_execute for migration
This patch introduces the next 2 migration scripts:
dx_apply and dx_execute.
dx_apply: creates the dataset hierarchy expected by linux upgrade
and unpacks the migration image within it. It also adds a new
entry in the FreeBSD bootloader so a VM can optionally boot from
Linux. Note that the script has a few WIP comments that are there
for 2 WIP issues. The first one is the fact that we can't do any
checks about running on the 5.3 release because of the feature
incompatibility of ZoL and our illumos pools (this is tracked by
LX-1633). The other one is a placeholder for the point of execution
where the migration scripts will run.
dx_execute: checks that dx_apply has left around all the expected
files and info and configures the …
=> LX-1551, LX-1553 - dx_apply & dx_execute 

live-build/misc/live-build-hooks/90-linux-migration-artifact.binary, live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute, live-build/misc/migration-scripts/dx_verify
This follows up on https://github.com/delphix/appliance-build/pull/167 and makes those scripts consumable by UpgradeManager.
The following changes had to be made:
- Add progress report to `dx_apply` and `dx_verify`
- Add a valid date field to `version.info`
- Reboot the system at the end of `dx_execute`
1. Run a 5.3 system through initial setup (Using `DRYRUN-migration-5.2.3.0` image)
1. Download migration image from S3 into /var/dlpx-update/upload
2. Remove `rpool/update` quota (`zfs set quota=none rpool/update`) as the migration image is very large and fails to unpack otherwise.
3. Run `dx_unpack` on the migration image
4. Go into the UI and click "Verify Upgrade" -- PASS.
5. Go into the UI and click "Apply Upgrade" -- This will apply the image and reboot into Linux. Note that domain0 …
=> Make migration image useable by UpgradeManager

live-build/misc/upgrade-scripts/upgrade-container
The "zfs-mount" service runs and works within the upgrade container, so
there's no need to explicitly bind mount "/var/dlpx-update" using the
container configuration file. Since the dataset backing that directory
is set up to automatically mount on boot, it'll automatically get
mounted within the container when the container boots up (as a result of
the "zfs-mount" service).
=> Use zfs-mount.service to mount datasets in container

live-build/misc/upgrade-scripts/upgrade-container
This reverts commit 20573a5d4ca5abe537c5f232b5ecf920a58286a0.
The change being reverted breaks not-in-place upgrade. This is due to
how we "debootstrap + start" the upgrade container, prior to installing
the delphix-entire package (and all of it's dependencies).
As a result, when the container is first started, the "zfs-mount"
service will not exist, and thus the "/var/dlpx-update" directory is not
automatically mounted. Then, because this directory isn't mounted, the
upgrade image required to execute the upgrade and install delphix-entire
is not accessible from the container.
The solution is to simply revert the breakage, and continue to rely on
systemd-nspawn to mount this container, since this works even when
delphix-entire is not installed in the container.
=> Revert "Use zfs-mount.service to mount datasets in container"

live-build/misc/upgrade-scripts/common.sh, live-build/misc/upgrade-scripts/upgrade-container, live-build/misc/upgrade-scripts/verify-impl
This change modifies where the upgrade-verify's JSON file will be
stored, from "/var/delphix/dropbox" to "/var/dlpx-update/verify-logs".
Since we already use "/var/dlpx-update/verify-logs" for storing the
support_info script's output, it makes sense to also use this directory
to store upgrade-verify's JSON file. This simplifies the container's
configuration, since we no longer need to bind mount the host's
"/var/delphix/dropbox" directory into the container.
=> Don't use "dropbox" for upgrade-verify's JSON file

live-build/misc/upgrade-scripts/common.sh
In commit 4bf0452d6018681f20680d2d71ea4d2a1554240d we incorrectly
removed the UPDATE_DIR variable from common.sh; as a result,
not-in-place upgrades are broken without this change.
=> Add UPDATE_DIR definition back to common.sh

live-build/misc/live-build-hooks/90-raw-disk-image.binary, live-build/misc/upgrade-scripts/upgrade-container
Use a dedicated/seperate dataset for grub, so that we can maintain it
differently than how we maintain and version the root filesystems. This
allows us to have a single configuration for the bootloader, spanning
all of the root filesystems that may be present on the system; rather
than trying to have a configuration on each root filesystem, and trying
to keep them all consistent with each other.
=> Use a dedicated dataset for GRUB configuration

scripts/run-live-build.sh
When we build an OVA for ESX, we first build a VMDK, and then convert
that into an OVA. We end up moving both artifacts to the artifacts/
directory, and thus we end up uploading both, but we really only need
the OVA.
=> Only copy OVA when building for ESX

upgrade/FAQ.md, upgrade/README.md, upgrade/upgrade-scripts/rootfs-container, upgrade/upgrade-scripts/upgrade, upgrade/upgrade-scripts/upgrade-container
This changes create a new upgrade script, rootfs-container, which can be
used to configure which "rootfs container" to be used as the appliance's
boot filesystem; i.e. the filesystem that will be used as the rootfs the
next time the system boots.
This logic had previously been contained in the "upgrade-container"
script's "convert_to_bootfs" function, so this change simply moves this
logic into a new script so it can be invoked seperately.
As an example, take the following system:
$ zfs list /
NAME                              USED  AVAIL     REFER  MOUNTPOINT
rpool/ROOT/delphix.a0Jj3pP/root  6.77G  32.2G     6.77G  /
$ sudo zfs list -r rpool/ROOT -d 1
NAME                         USED  AVAIL     REFER  MOUNTPOINT
rpool/ROOT                  31.6G  32.2G       65K  none …
=> Add script to choose which rootfs to boot next

bors.toml
For our Jenkins job that executes the build, we use a 12 hour timeout.
Thus, we should align the timeout we use for bors to align with that, so
bors doesn't result in a timeout while the build is still in progress.
=> Bump bors timeout to align with Jenkins timeout

upgrade/upgrade-scripts/execute
This change adds some logic to the "execute" upgrade script to verify
the package dependencies of the delphix-entire package match the
packages (and their versions) that are actually installed.
Closes #205
=> Verify delphix-entire package dependencies

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute
`/var/delphix` contains some Delphix configuration and useful debug logs, so we want to carry that directory over into Linux. Note that we do that in `dx_execute` since that's when the stack is quiesced.
There's also a side fix to the code that edits `/etc/fstab` as it didn't seem to work consistently.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/503/
- verify that  `/var/delphix` was carried over after rebooting into Linux:
```
delphix@localhost:/var/delphix$ df .
Filesystem                      1K-blocks  Used Available Use% Mounted on
rpool/ROOT/delphix.WhJtaCV/data 116131072  4864 116126208   1% /var/delphix
delphix@localhost:/var/delphix$ zfs get origin rpool/ROOT/delphix.WhJtaCV/data
NAME …
```
=> LX-1747 /var/delphix dataset should be migrated to Linux

live-build/config/hooks/90-linux-migration-artifact.binary
We recently had a failure where the logs looked like this:
```
00:28:45 + set -o pipefail
00:28:45 + jq -r .signature
00:28:45 + curl -s -f -H 'Content-Type: application/json' -u **** ****/upgrade/keyVersion/5.3/sign -d @-
00:28:45 + base64 -d
00:28:45 ++ base64 -w 0 depot/hashes
00:29:12 E: config/hooks/90-linux-migration-artifact.binary failed (exit non-zero). You should check for errors.
00:29:12 P: Begin unmounting filesystems...
00:29:12 P: Saving caches...
00:29:12 Reading package lists...
00:29:12 Building dependency tree...
00:29:12 Reading state information...
00:29:12 + kill -9 1037
00:29:12 + [[ ! -f binary/SHA256SUMS ]]
00:29:12 + exit 1
```
It is hard to tell exactly what went wrong because the
specific shell statement in questions is a long pipe of
commands.
This patch …
=> Refactor signature generation for migration to ease debugging

live-build/misc/ansible-roles/appliance-build.minimal-internal/tasks/main.yml
On the internal variants, we have cloud-init configured to read EC2
userdata, which we use to set up SSH keys on newly-provisioned VMs in
EC2. We should also allow cloud-init to read userdata from GCP, so that
we can set up SSH keys on internal Delphix engines there too. The
devops-gate has a workaround in place such that reading userdata from
Azure isn't strictly necessary, but we might as well add it while we are
at it so that that workaround can be removed.
=> Add additional cloud-init datasources for internal variants

live-build/misc/ansible-roles/appliance-build.minimal-internal/tasks/main.yml
The original change broke cloud-init on the ESX. Reverting until we figure out the correct way to make this change.
=> Add additional cloud-init datasources for internal variants (revert)

upgrade/upgrade-scripts/upgrade, upgrade/upgrade-scripts/verify, upgrade/upgrade-scripts/verify-jar, upgrade/upgrade-scripts/verify-stack
Adds stack startup verification logic.
* The stack startup verification logic will run only if it's a reboot required upgrade (i.e. when current version is less than `MINIMUM_REBOOT_OPTIONAL_VERSION`. Once a container packages are upgraded to the latest version, we don't have a way to get the previous version to compare against `MINIMUM_REBOOT_OPTIONAL_VERSION`. So I simply save the pre-upgrade version to `${IMAGE_PATH}/${UPGRADE_VERSION_FILE_NAME}` before running `execute` script and read the content before verifying.
* In order to run stack within a container, we need have a copy of MDS instance. In order to do so, we leverage `dx_manage_pg.sh` script to make a copy of MDS, start and stop the instance. Once MDS clone is prepared, we need to create new links to `/var/delphix/server/db` …
=> LX-1337 Allow app-gate stack to run in a chroot (systemd-nspawn) environment

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute
This adds the logic to execute the migrate_config script that performs the OS configuration migration during a migration upgrade.
This also adds a flag file consumed by the delphix-migration service informing it that it has work to do.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/605/
- Tested manual migration in conjunction with https://github.com/delphix/delphix-platform/pull/55 (See that PR's testing section for more details)
=> Run pre-reboot config migration logic

upgrade/upgrade-scripts/verify-jar, upgrade/upgrade-scripts/verify-stack
These two were regressions caused by LX-1337. My apologies.
LX-1784 Upgrade verify fails due to lack of permission
* New scripts, `verify-jar` and `verify-stack` didn't have an execute permission. 
LX-1785 MDS clone isn't cleaned up after verification
* `zfs list <dataset_name>` takes full dataset path, not just part of it, so the snapshot names should appended by `domain0`.
Tested on failed VM.
=> Fix for LX-1784 and LX-1785 MDS

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute
Adding the same command line arguments as we have in https://github.com/delphix/delphix-platform/blob/master/etc/default/grub.d/override.cfg. Note that we should make a follow-up change to set the default serial port baud rate in the console to 115200 for regular Linux installations instead of the current 38400.
Ultimately we just needed to add 2 parameters to the command line passed to the kernel:
```
'ipv6.disable=1'
'crashkernel=1024M-:512M'
```
However, after adding those parameters to the original script, the bootloader would fail to boot with our new string:
```
fail at line 179
Parse error!
```
After doing some testing it appears that the bootloader interpreter has a 256 characters limit for any command entered in the `ok` prompt, preventing us from typing the full command, and …
=> LX-1783 migration: reconcile /proc/cmdline between migration and initial install

live-build/misc/migration-scripts/dx_execute
This workaround is put in place to unblock migration testing, until we figure out how to properly handle migration of analytics.
* ab-pre-push (build only) http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/656/
* blackbox-chained to perform migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/21/
* Verified that the stack comes up after migration without hitting this bug.
=> migration: Workaround for LX-1779: remove analytics slices and data

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
At delphix we use Jenkins to automate and monitor common tasks. One way of
handling tasks that involve remote servers is to use them as Jenkins agents,
which requires that the agents be running the same version of Java as the
Jenkins masters, which is currently java 8. For this change, I install Java 8
on all new dcenter servers so that Jenkins can work with them.
I installed this on the currently running dcenter and am using it as a Jenkins
agent.
=> Add openjdk to the dcenter build.

live-build/misc/migration-scripts/dx_execute
Together with the app-gate work in http://reviews.delphix.com/r/48049/, this makes sure that on the first stack startup after a migration is performed we mark the upgrade as successful.
This PR should be pushed after the app-gate is pushed.
migration testing: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/36/
=> Create upgrade.properties during a migation upgrade

live-build/misc/migration-scripts/dx_verify
**Overview**
This is based very closely on the `dx_verify` for illumos upgrades. The main differences are as follows:
1. Always mount the root dataset since the migration is always a full OS upgrade and we need access to the contents on the migration image
2. Invoke `UpgradeVerify.jar` with a migration option to indicate that it is being run in the context of a migration. 
3. Do some initial dummy file creation for `whitelist` and `stress_options`. 
The remaining work to be done in this script relates to setting up the datasets for and running the masking checks. It's tracked in LX-1771.
**Testing**
+ Run testing automation with chain jenkins job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/43/consoleFull
Reboot into Linux succeeded, all services …
=> LX-1552 need a dx_verify for migration

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/rootfs-container, upgrade/upgrade-scripts/upgrade, upgrade/upgrade-scripts/upgrade-container
This change enables rollback for in-place upgrades. It does this by
creating a new type of upgrade container; a "rollback" upgrade
container. This container type can only be created after an in-place
upgrade has been performed, as it relies on the snapshots that are
created by the "execute" script during an "in-place" upgrade.
During rollback after an in-place upgrade, a "rollback" upgrade
container will be created, and then this container is immediately
converted into the rootfs/bootfs container. Thus, after the rollback
operation and a subsequent reboot, that rollback container will be the
mounted rootfs.
=> Support "rollback" for in-place upgrades

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
This change modies upgrade and rollback to use the "upgrade.properties"
file, so that upgrading and rolling back via the command line (i.e. via
the upgrade scripts) integrates better with the upgrade and rollback
logic contained in the virtualization application.
The goal(s) being:
1. If an upgrade occurs via the command line, the virtualization logic
should be able to detect this and roll the upgrade back, if the
virtualization application determines the upgrade to have failed.
2. If the upgrade occurs via the virtualization application, we should
be able to rollback the upgrade via the command line.
3. If the upgrade occurs via the command line, rollback via the command
line should continue to work.
4. If the upgrade occurs via the virtualization application, rollback
via the …
=> Use the "upgrade.properties" file for upgrade/rollback

live-build/config/hooks/vm-artifacts/90-linux-migration-artifact.binary
We recently had a couple jobs fail because a request made using `curl` failed. However, we don't know what the error was because we use the `-s`/`--silent` flag. This change adds the `-S` flag, which makes `curl` print errors when it fails.
=> Print curl errors

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute
The current 1 second timeout is often too short to be able to choose the right bootloader option through the ESX console or the serial console on dcenter.
As we are getting ready for the Lumen migration being able to have more time in the bootloader could become more critical to insure better supportability.
- Created image: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/833/
- Tested that migration works
- Verified that bootloader timeout was actually increased to 20 seconds
=> LX-1812 Increase freebsd bootloader timeout

scripts/build-ancillary-repository.sh, scripts/build-upgrade-image.sh
By default, `aptly publish repo` generates "Contents" indices. Per [the Debian Repository Format specification](https://wiki.debian.org/DebianRepository/Format#A.22Contents.22_indices), these are "optional indices describing which files can be found in which packages." Our build and upgrade process does not use these indices, but they require several minutes to generate (see aptly-dev/aptly#345). We can save time during our build by skipping this unnecessary step. This change adds the `-skip-contents` option whenever we invoke `aptly publish repo`.
On our two-core build VMs, the change results in a modest but noticeable performance improvement. For example, we save over 5 minutes when generating each upgrade image. Before:
```
06:21:20 + aptly publish repo -skip-signing upgrade-repository …
```
=> Skip generation of "Contents" indices when running aptly(1).

live-build/misc/migration-scripts/dx_verify
**Overview**
These changes are also based very closely on the original `dx_verify`. The main differences are related to the `dmsuites`/`masking` name change. 
Prepare the `/var/delphix` clone required for the Flyway migration job in `MDSVerify` and run the masking properties check.  
**Testing**
_Automated_ 
Chained migration job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/80/console
Job completed successfully, all services started as expected:
```
> systemctl list-units --state=failed 
0 loaded units listed.
```
_Manual_
Set up an engine using a masking blackbox suite and checked that the masking properties check worked as expected with real values in the `override.properties` file.
Made a bogus masking property and saw that the appropriate …
=> LX-1771 Run masking upgrade checks from dx_verify

live-build/config/hooks/upgrade-artifacts/82-upgrade-repository.binary, live-build/config/hooks/vm-artifacts/91-gce-machine-image.binary, scripts/build-upgrade-image.sh
`pigz(1)` is a parallel implementation of `gzip(1)` which speeds up builds by taking advantage of multiple cores. `tar -I pigz` is a drop-in replacement for `tar -z`.
This change replaces all calls to `tar -z` with `tar -I pigz`. Note that according to [the `pigz(1)` man page](https://manpages.ubuntu.com/manpages/bionic/man1/pigz.1.html), "decompression can't be parallelized […]. As a result, `pigz` uses a single thread (the main thread) for decompression." Therefore, I have only modified the `tar` invocations that pertain to compression rather than the invocations that pertain to decompression.
On our two-core build VMs, the change results in a modest but noticeable performance improvement. For example, we save 2.5 minutes building the GCP image. Before:
```
37:25 + tar -z --transform …
```
=> Use pigz(1) when compressing tarballs.

upgrade/upgrade-scripts/upgrade-container
As noted in the bug, we are seeing a default `/etc/issue` file present on VM upgraded with "not-in-place" upgrade.
**Cause**
* The current implementation of `migrate_file` function only migrates the file to the container if it exists on the host. This means if a host doesn't have the file but the container somehow does, then it'll leave the file in the container.
This case happens with `/etc/issue` file where host doesn't have the file, but the `not-in-place` container created it while executing`debootstrap` which has the content "Ubuntu 18.04.2 LTS \n \l".
**Fix**
* We force delete the migration target file on the container file system if the file doesn't exist on the host.
=> LX-1826 /etc/issue file created/populated after not-in-place upgrade

upgrade/upgrade-scripts/upgrade-container
This change adds the following directories to be migrated on upgrade:
* /var/lib/nfs
* /var/target/pr
=> Migrate two more directories on upgrade

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute, live-build/misc/migration-scripts/dx_verify
This makes sure that any directory created by the migration script has the default umask.
See https://jira.delphix.com/browse/LX-1852 for more details.
build image: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/929/
Run migration and perform some checks:
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/104/ (failure of the job is expected)
- Make sure cli works
- Verify that `/export` has the right permissions set.
=> LX-1852 migration: Failure to access CLI after migration

live-build/misc/ansible-roles/appliance-build.minimal-development/tasks/main.yml
For developer convenience, add the repositories containing debug symbol packages in `/etc/apt/sources.list.d/` so that dbgsym packages can be installed on a new `internal-dev` VM without any extra steps.
=> Add repositories for debug symbol packages

upgrade/upgrade-scripts/verify-jar
This is a part of a larger change to upgrade verify UX. The user can now view the verification steps.
Some PRE-verify steps are included in the report so that it is relatively in-sync with the messaging in the action pane, and the time spent waiting for verify to complete.
This change is a dependency for this app-gate commit:
http://reviews.delphix.com/r/48499/
=> verify-jar : add support for 4 new long parameters for initialization timestamps

live-build/misc/ansible-roles/appliance-build.minimal-development/tasks/main.yml
This reverts commit 6e4b9b782fe856f1eead34387190e22d433c2855.
Copied from evaluation of `DLPX-63959`
> The failing commit is this: https://github.com/delphix/appliance-build/commit/0210db1a31817bb0e075aecbacec88579de6d51f
As I mentioned in the previous comments, the problem is that `apt-get update` from the `execute` is failing because `cloud-init` is already holding the apt repository lock, preventing other apt update to fail.
From the source code of cloud-init (https://github.com/cloud-init/cloud-init/blob/ubuntu/bionic/cloudinit/config/cc_apt_configure.py#L629) we see that it does a apt-get update once it sees a apt.sources: list in the configuration file and the failing PR noted above did add apt.sources:.
The proper fix is currently under discuss and we are leaning toward solving the …
=> Revert "Add repositories for debug symbol packages" (Causes DLPX-63959)

live-build/misc/migration-scripts/dx_delete
The `dx_delete` logic isn't compatible with Linux dataset layout so the post upgrade verification cleanup logic fails. To be more specific, upgrade verification workflow is as follows:
1. Calls `dx_apply` which creates datasets for the new upgrade
2. Performs upgrade verification
3. Calls `dx_delete` which cleans up the datasets.
As @pzakha noted in the bug ticket, we need to 
1. Change `dx_delete` to support Linux dataset layout. 
2. App-gate should consume `dx_delete` **provided from the upgrade image** rather than the one in currently running version since layout may change in the future.
The fix requires two changes
1. Add a new `dx_delete` script in migration image which handles deleting Linux datasets. It looks for `rpool/ROOT` dataset which is Linux dataset prefix and recursively …
=> DLPX-63098 Rework dx_delete

live-build/misc/ansible-roles/appliance-build.crash-python-development/tasks/main.yml
We install the pip apt package and then use it to install mypy.  Tested by building an internal dev kvm image and verifying that mypy is installed and runnable:
```
delphix@localhost:~$ mypy --version
mypy 0.701
```
=> Add new mypy version to crash-python dev role

live-build/misc/ansible-roles/appliance-build.minimal-internal/tasks/main.yml
See https://github.com/delphix/delphix-platform/pull/81 for more details.
=> Allow public keys to be passed for internal builds with new cloud-init changes

live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary, live-build/misc/migration-scripts/dx_apply, upgrade/upgrade-scripts/upgrade-container
I noticed that the zfs-import-cache.service and the dynamically created fstab mount services would try to run at the same time. The import logic would grab the `spa_namespace_lock` and prevent local mounts to rpool from completing. Eventually the mounts would timeout which would cause the system to come up and appear hung:
> May 10 19:05:31 localhost systemd[1]: Mounting /export/home...
> May 10 19:07:01 localhost systemd[1]: export-home.mount: Mounting timed out. Terminating.
> May 10 19:07:01 localhost systemd[1]: export-home.mount: Mount process exited, code=killed status=15
> May 10 19:07:01 localhost systemd[1]: export-home.mount: Failed with result 'timeout'.
> May 10 19:07:01 localhost systemd[1]: Failed to mount /export/home.
This change ensures that the local legacy mounts …
=> legacy mounts can timeout waiting for zpool import service to complete

upgrade/upgrade-scripts/execute
There has been `apt` lock issues in the past and the problem is that we can't predict and prevent what other processes are holding the lock.
E.g.
```
Reading package lists...
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
This message also doesn't provide any further debugging message to fix the error.
Adds a wait function with a debugging statements to check if there are other processes holding the `/var/dpkg/lib/lock` or `/var/dpkg/lib/lock-frontend` for a fixed timeout of 5 min. IMO 5 min should be sufficient since it's unlikely there are other process that installs numerous packages. In case timeout occurs we can inspect `pstree` …
=> DLPX-61762 Linux verify fails, Unable to acquire the dpkg frontend lock

live-build/misc/migration-scripts/dx_apply
After https://github.com/delphix/delphix-platform/pull/93, we no longer expect to see the `dropbox` directory in the migration image. Remove the relevant check in `dx_apply`
Appliance build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1260/
Chained migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/249/
=> Remove check for dropbox in migration dx_apply

live-build/misc/ansible-roles/appliance-build.minimal-internal/tasks/main.yml
Re-enable cloud-init on all cloud platforms. We achieve this by using the default `datasource_list` from cloud-init.
This must be pushed after https://github.com/delphix/delphix-platform/pull/94 and https://github.com/delphix/cloud-init/pull/7 are integrated.
- git-ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1266/
(linux-pkg build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/117/)
- Launched a VM created from an image for each supported platform and verified that cloud-init works properly.
- Made sure that networking is configured properly for a VM cloned from the ESX image on dcenter. Made sure that networking is also working properly …
=> DLPX-64347 Enable cloud-init on all platforms

upgrade/upgrade-scripts/execute
This reverts commit 9da3c1e6835d975e1a2bf46147420d7b0720fcb3.
=> Revert "DLPX-61762 Linux verify fails, Unable to acquire the dpkg frontend lock"

live-build/misc/migration-scripts/dx_execute
dxsvcinit has been silently failing to take a snapshot on migration because we do not set the base version in the migration case
```
Jun 07 08:22:52 dlpx-5350-QAR-563f3ba9.dc4 systemd[1]: Starting Delphix default PostgreSQL database server...
Jun 07 08:22:52 dlpx-5350-QAR-563f3ba9.dc4 svc-postgres[5819]: dxsvcinit: missing UPGRADE_BASE_VERSION peroperty
```
This bug was exposed when working on this app-gate change: http://reviews.delphix.com/r/49923
Testing on app-gate review
=> DLPX-64339 Remove/refactor Illumos specific scripts/code blocks

live-build/misc/ansible-roles/appliance-build.minimal-internal/tasks/main.yml
Backport cloud-init changes to get a working external-standard OVA
=> Backport cloud-init changes to projects/6.0-ea

live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
`ant(1)` is needed to run unit tests.
=> Add ant to internal-unittest variant

live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
`build-essential` is needed to run the Masking Engine unit tests on the `internal-unittest` variant. Without it, they fail with this error:
```
Execution failed for task ':mountScripts:compileMountFilesystemExecutableMountFilesystemC'.
> No tool chain is available to build for platform 'linux_x86-64':
- Tool chain 'visualCpp' (Visual Studio): Visual Studio is not available on this operating system.
- Tool chain 'gcc' (GNU GCC): Could not find C compiler 'gcc' in system path.
- Tool chain 'clang' (Clang): Could not find C compiler 'clang' in system path.
```
=> Add build-essential to internal-unittest variant

build.gradle, scripts/build-upgrade-image.sh, upgrade/prepare
This review introduces a new prepare script in the delphix upgrade image. This new script completes the unpack process and is invoked from the unpack-image script from current_version engine where the upgrade image is uploaded to. Corresponding changes to unpack-image are in PR https://github.com/delphix/delphix-platform/pull/106 along with more details on the design and necessity.
git-ab-pre-push CLEAN run: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1527/
=> DLPX-63558 update unpack-image script in Lumen to accept future wrapper upgrade image and hand-off to complete-unpack script

live-build/config/hooks/vm-artifacts/90-linux-migration-artifact.binary, live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute
ab-pre-push (esx):
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1533/
BB-chained:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1536/
manual-migration (negative test - migration from 5.3.4.0) -
Verification gives error:
```
Error:
The minimum version required for this upgrade is "5.3.5.0". The Delphix Engine is currently running version "5.3.4.0".
Error Code:
exception.upgrade.current_too_old
Suggested Action:
Upgrade to an interim version that is equal to or newer than the minimum required.
```
=> LX-1633 Enable 5.3 version checks for dx_apply in migration

upgrade/prepare
DLPX-64972 fix shellcheck issue in prepare script in appliance-build repo
original fix in below commit from delphix-platform repo (https://github.com/delphix/delphix-platform/commit/fd777edfddba0725539406d332bdc67cc168307f)
This was missed since code was moved to appliance-build. Noticed it when I was ready to merge the delphix-platform PR to update unpack-image to remove the redundant code.
commit fd777edfddba0725539406d332bdc67cc168307f
Author: Pavel Zakharov <pavel.zakharov@delphix.com>
Date:   Thu Jun 27 13:01:19 2019 -0400
fix shellcheck issue
testing :
git ab-pre-push CLEAN : http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1569/
=> Fix shellcheck that was missed in this code was moved from delphix-platform unpack-image script.

live-build/misc/migration-scripts/dx_execute
This removes the workaround that was added via [PR-244](https://github.com/delphix/appliance-build/pull/244/).
Tests
* On a 5.3.5 DDP that had both NFS and iSCSI basic workloads running -  verified pre-migration that analytics subsystem working for all default statistic slices and that post-migration,  the same transitions/migrates over without any errors. See JIRA for more verification details.
* ab-pre-push - http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1585/console
=> DLPX-64699 migration: Analytics attempts to launch dtrace on Linux

upgrade/README.md, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
We want to be able to upgrade our dcenter instances on a nightly basis and the plan is to use "deferred" upgrades to ensure that we don't see any kernel/userland inconsistencies. This change allows the user to select either "deferred" or "full" upgrades similar to our application stack. For "full" upgrades, it will determine if a not-in-place upgrade is required.
=> upgrade script should be able to do deferred upgrades

upgrade/upgrade-scripts/upgrade-container
As pointed out in http://reviews.delphix.com/r/50896/, we need to remove `/etc/engine-uuid` from the list of files to be copied for Linux upgrades.
=> CP-2777 CRA enabled for Linux (cleanup)

live-build/misc/migration-scripts/dx_verify
Previously, when we invoked the `upgradeVerify` jar, we passed a bash variable as a flag which is populated if debug is on, and is empty if it is not. This means that when debug mode is off, `java` is passed `""` and doesn't know what to do with it. 
This solution means the debug mode will always be specified. 
Tested manually with debug mode on and off.
`git-ab-pre-push --test-upgrade-from 5.3.6.0`: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1766/
=> DLPX-64524 Migration fails during dx_verify when debug mode is off

live-build/config/hooks/vm-artifacts/template.ovf
DLPX-64726 Unable to parse 'enableMPTSupport' warning when deploying OVA
DLPX-65248 Lumen OVAs are being built with HWv9
=> Cleanup OVA template

live-build/misc/migration-scripts/dx_execute, live-build/misc/migration-scripts/dx_upg_pause_options, live-build/misc/migration-scripts/dx_upg_stress_options
This adds the pause and stress options scripts to the migration image.
Note that for now the scripts are taken as is from the 5.3/stage branch. They have been slightly modified to comply with the shell format checks.
Note that we are going to add some new options and remove those that do not apply to migration in follow-up work, as we will be iterating on the migration-specific stress tests.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1772/
=> Add pause and stress options scripts to migration images

live-build/misc/migration-scripts/dx_apply, upgrade/upgrade-scripts/upgrade-container
This change works with an associated app-gate change that uses the cached UUID in place of the system's detected UUID if the cached version and the system's version are potentially byteswapped versions of each other.
Tested by migrating aws 5.3.5.0 VM, verified that reported UUID remained the same. In addition, ab-pre-push testing is in progress.
=> Store engine uuid before migration

live-build/misc/migration-scripts/dx_execute
Adds upgrade reboot screen to migration upgrades, using dx_execute code from 5.3.
- manually verified that the reboot screen appears in the UI.
- git-ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1889/
=> DLPX-65387 Upgrade rebooting screen is no longer observed upgrading from 5.3.5 to L

live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml, upgrade/upgrade-scripts/upgrade-container
This change causes our virtualization images to ship with an NFSv4-only NFS server configuration by default out of the box. The virtualization software is responsible for dynamically enabling NFSv3 services as needed. This is being implemented in http://reviews.delphix.com/r/50851. Without the dlpx-app-gate changes, the virtualization software will not be able to mount NFSv3-based VDBs, so those changes must integrate before this PR is merged into appliance-build.
There are three changes implemented here:
1. The ansible task that creates the initial NFS server configuration in `/etc/default/nfs-kernel-server`. Note that this code previously lived in dlpx-app-gate, and is being removed from there as part of http://reviews.delphix.com/r/50851. It is being moved here because this is one-time …
=> Ship with an NFSv4-only configuration by default.

live-build/build.gradle, live-build/config/hooks/configuration/81-upgrade-repository.binary, live-build/config/hooks/vm-artifacts/90-linux-migration-artifact.binary
In the past the version of the `delphix-virtualization` package would be used to determine the version of the appliance. This was changed, but we forgot to update the logic when generating the migration image.
- manually tested building a variant with `DELPHIX_APPLIANCE_VERSION` set and unset on a `bootstrap-18-04` system.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1896/
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1895/
- Check that after performing a migration we do not see 2 versions anymore: **TODO**
=> DLPX-65345 Applying L early release migration image results in two upgrade versions being created

upgrade/upgrade-scripts/upgrade-container
- We copy all cloud-init directories that are related to cloud init cache, that is:
`/var/lib/cloud/{data, instance, instances, sem}`
We do not copy the whole `/var/lib/cloud` directory as it contains directories/files managed by other packages (e.g. `/var/lib/cloud/seed`)
- We copy the auto-generated network configuration:
`/etc/netplan/50-cloud-init.yaml`
Note that this file may not be present if the default network configuration was modified. In that case `/etc/netplan/10-delphix.yaml` and `/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg` should be present instead.
- We copy the `/etc/hosts` template file:
`/etc/cloud/templates/hosts.debian.tmpl`
This is the file that is used by cloud-init to auto-generate `/etc/hosts`, so any changes that support wants to make to `/etc/hosts` …
=> DLPX-64429 not-in-place upgrade should copy files related to cloud-init

build.gradle, live-build/misc/migration-scripts/dx_verify, live-build/misc/migration-scripts/etc_system_whitelist
When migrating from Illumos to Linux, we want to use the existing `EtcSystemWhitelistCheck` from `UpgradeVerify` to make sure that customers have not modified system variables that will not be preserved. 
This check relies on the existence of a whitelist file in the `/var/dlpx-update/<version>` directory. In regular upgrade, it was stored as a `resources` file in the app-gate and placed in the upgrade image as part of the build. Because we use the `appliance-build` gate to build the migration image, I figured placing it here would be a simple solution. This strategy also allows for different whitelist entries between upgrades and migration, if required.
For now, keeping the entries identical makes sense to me. I checked that all the `zfs` tunables in the whitelist still exist and can be …
=> LX-1817 /etc/system whitelist file and check for migration

.gitignore, upgrade/upgrade-scripts/upgrade-container
Removed the code where `/var/tmp/delphix-upgrade` folder is created and shared with container. 
This is not necessary anymore as going forward we will have that folder mounting the dataset which will be shared across versions.
=> DLPX-65276 Create new dataset that will be shared across versions to store rollback and verify logs

live-build/misc/migration-scripts/dx_execute
LX-1780 migration: snapshot should be taken before doing changes to MDS
DLPX-65365 After upgrading from 5.3.5 to L, the delphix user's home directory was wiped clean
- Snapshots taken for migration are now called `@migration` to make it easier to clean them up later.
- Take a snapshot of MDS before reboot to make rollback easier/safer.
- Make a clone of the illumos /export/home dataset to make it easier for support to retrieve old scripts.
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1932/
- After migration, manually test mounting `rpool/illumos-home`, and cleanup of the old illumos datasets after using `zfs promote`.
=> Fixes for LX-1780 and DLPX-65365 related to migration

scripts/build-upgrade-image.sh, scripts/docker-run.sh
This changes which keys are used when signing the upgrade image.
Previously we used a hardcoded value of 5.3, and thus we always signed
the upgrade image with the 5.3 key. Now, we require the user to specify
a space seperated list of versions, and we sign the upgrade image with
the key corresponding to each version in the list.
This is intended to work inconjunction with some Jenkins changes, where
Jenkins will build the correct list of signature versions, based the
specific version of the upgrade image being built.
=> Require DELPHIX_SIGNATURE_VERSIONS to be passed in

README.md, scripts/build-upgrade-image.sh, upgrade/README.md
The file we use for the upgrade image is better left uncompressed
because most of its contents is already compressed. Thus, by having
the file compressed as well, we're mostly wasting resources attempting
to compress (and later decompress) data that is already compressed.
If we leave the file uncompressed, it's actually slightly smaller in
size, than the compressed version of the same data:
$ du -k internal-dev.upgrade.tar*
5615228 internal-dev.upgrade.tar
5616954 internal-dev.upgrade.tar.gz
$ file internal-dev.upgrade.tar*
internal-dev.upgrade.tar:    POSIX tar archive (GNU)
internal-dev.upgrade.tar.gz: gzip compressed data, last modified: Tue Aug 27 12:54:30 2019, from Unix
$ tar --list -f internal-dev.upgrade.tar
SHA256SUMS.sig.5.3
SHA256SUMS
version.info
prepare
payload.tar.gz
$ tar …
=> Upgrade image file is better left uncompressed

scripts/build-upgrade-image.sh, scripts/docker-run.sh, upgrade/version.info.template
This change modifies how we populate the "version.info" file of an
upgrade image. Rather than having the "minimum version" and "minimum
reboot optinal version" fields be stored directly in the template file,
we now rely on the caller to pass in those files. Generally, this will
be passed in by our Jenkins automation.
=> Rely on caller to provide upgrade minimum versions

live-build/misc/migration-scripts/dx_upg_stress_options
This adds a bunch of stress options to test failures during migration.
This is not the final set of options but this will allow implementing QA tasks.
- app-gate: http://reviews.delphix.com/r/52088/
- delphix-platform: https://github.com/delphix/delphix-platform/pull/122 (should be pushed last)
Write BlackBox tests to trigger those options and test that migration can successfully complete.
- ab-pre-push, including related changes: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2004/
- manually test roll forward: set 2 of the stress options before upgrade, perform upgrade, and observe delphix-migration failing at boot time. Run `migrationctl resume` to resume the migration, which first triggers then second stress options. Run it …
=> LX-1948 migration: add first round of stress test options (appliance-build part)

live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary, live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute, upgrade/upgrade-scripts/upgrade-container
Turning on compression on rpool makes sure it is inherited
by all the other datasets, so we do not need to set it
explicitly on each dataset we create.
Simplify our ZFS setup and reduce differences between Linux native and migrated systems.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2022/
- migration: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2023/
- Manually verified that compression was set on all datasets on a fresh Linux system and after a migration.
=> Use compression on rpool by default

live-build/config/hooks/vm-artifacts/90-linux-migration-artifact.binary, live-build/misc/migration-scripts/dx_apply
`git-ab-pre-push -a --test-upgrade-from 5.3.6.0`:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1991/
^ linux-precommit at dx-test failed because of unrelated known failure
`git-ab-pre-push -a --test-upgrade-from 5.3.5.0`:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1992/
^ Failed as expected with the following message:
```
[2019-08-23T04:33:02.780Z] !!!!!!!!!!!!!!!!!!!
[2019-08-23T04:33:02.780Z] Details: The minimum version required for this upgrade is "5.3.6.0". The Delphix Engine is currently running version "5.3.5.0".
[2019-08-23T04:33:02.780Z] Action: Upgrade to an interim version that is equal to or newer than the minimum required.
[2019-08-23T04:33:02.780Z] …
```
=> DLPX-65496 Re-adjust dx_apply version checks for migration

.travis.yml
We've been seeing timeouts when building the Docker container used with
our TravisCI testing. If a command doesn't produce any output for 10
minutes, TravisCI will fail the build the command is running in. Thus,
if "docker build" takes longer than 10 minutes to build the image, our
builds would fail because we had been using the "-q" option when
building the image.
This change removes the "-q" option so that the "docker build" command
will output text as it builds the image, and this output will keep
TravisCI happy even if it takes more than 10 minutes to build the image.
=> Don't use "-q" when building Docker image

upgrade/prepare
Instead of tags unpack script will accept different exit codes that will be translated in app-stack.
Corresponding app-gate change: http://reviews.delphix.com/r/52590
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2193/
=> DLPX-65501 uploading same upgrade image twice has "unexpected" error

branch.config, scripts/build-ancillary-repository.sh, scripts/docker-run.sh, scripts/run-live-build.sh
Add functionality to appliance-build to infer the latest linux package mirror dataset for builds if no mirror url is passed in. 
Testing:
Ran git ab-pre-push 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2212/parameters/
=> LB-209 Want to consume new mirror for production appliance build

scripts/build-ancillary-repository.sh
linux-pkg now output the `.ddeb` packages that it produces. To make them available for installation, we just need to add them to our ancillary apt repo.
=> Make debug symbol packages (ddebs) available for installation

scripts/build-ancillary-repository.sh
=> [Backport to 6.0] Make debug symbol packages (ddebs) available for installation

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_delete, live-build/misc/migration-scripts/dx_verify
Backport of https://github.com/delphix/appliance-build/pull/381
`git-ab-pre-push --test-upgrade-from 5.3.6.0`: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2401/
=> DLPX-66331 [Backport of Issue DLPX-66286 to 6.0.0.0] Interrupting a running upgrade verify can leave the engine not-upgradable

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_delete, live-build/misc/migration-scripts/dx_verify
Extending `dx_delete` for migration to clean up the state of verify, even when it was cancelled in the middle of an operation. This includes: undoing changes to the bootloader, removing the MDS clone service and datasets and destroying `rpool/ROOT` using `-f`, which force unmounts its children as well. 
This was all based on what `dx_apply` and `dx_verify` do to clean up after themselves and replicating that logic in `dx_delete` so we can guarantee ending up in a "clean" state if we're cancelled or fail unexpectedly. 
I manually tested this by running a verify and cancelling it at various stages (roughly during `dx_apply` and `dx_verify`), ensuring that the cancel succeeded and then checking that a subsequent verify can run successfully as well. 
Automated testing: 
`git-ab-pre-push …
=> DLPX-66286 Interrupting a running upgrade verify can leave the engine not-upgradable

live-build/misc/migration-scripts/dx_apply
This migration change is equivalent to https://github.com/delphix/delphix-platform/pull/155 PR
=> DLPX-66946 Set 'elevator=noop' GRUB option for first boot after migration

live-build/misc/migration-scripts/dx_apply
`dx-delete` will restore the old bootloader menu before the Linux dataset was dx-applied, effectively removing all the new linux entries.
Regarding the cleanup of `rpool/ROOT`, dx-delete takes care of it, so we can remove the now redundant logic.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2414/
=> DLPX-67184 migration: dx_apply should call dx_delete to cleanup previous state

live-build/misc/migration-scripts/dx_apply, live-build/misc/migration-scripts/dx_execute, live-build/misc/migration-scripts/dx_upg_stress_options, live-build/misc/migration-scripts/dx_verify
Add stress options to `dx_apply`, `dx_verify` and `dx_execute` to make sure that the pre-upgrade migration processes can recover from unexpected failures. 
I found that after hitting `STRESS_DX_EXECUTE_FAIL_BEFORE_REBOOT`, `cleanup_leftover_dataset` in `dx_excute`  fail to destroy snapshots with residual clones, so I added `-R` to clean those up. I also renamed `STRESS_DX_VERIFY_FAIL_AFTER_TEST_MIGRATION` for clarity. 
Manually tested that when set, the stress options do cause the scripts to fail at the expected point. Confirmed that the prior state of the failed runs was cleaned up and the run was successful.
`git-ab-pre-push --test-upgrade-from 5.3.6.0`: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2452/
=> DLPX-66696 migration: add stress options in the pre-reboot dx scripts

live-build/misc/migration-scripts/dx_apply
This backports https://github.com/delphix/appliance-build/pull/388.
- migration ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2454/
=> DLPX-67336 [Backport to 6.0.0.0] migration: dx_apply should call dx_delete to cleanup previous state

live-build/config/hooks/vm-artifacts/83-etc-resolv-conf.binary, upgrade/upgrade-scripts/upgrade-container
At boot time, applications will fail to resolve the local hostname
to an IP address (i.e. the loopback address) until DNS servers are
reachable, and once they are reachable, such lookups will result in
external DNS requests, which is suboptimal given how often applications
resolve the local hostname. These lookups should all be done locally
without relying on external DNS servers.
When applications resolve a hostname to an IP address, they use the NSS
switch, which has a policy for how lookups should be done. On Delphix,
the hosts entry for /etc/nsswitch.conf looks like this:
```
hosts:          files dns mymachines
```
This means that any lookup will first consult local files (/etc/hosts),
and if that fails, will go out to DNS. The /etc/hosts file is managed
by cloud-init, and will …
=> DLPX-66957 hostname is not locally resolvable

live-build/config/hooks/vm-artifacts/83-etc-resolv-conf.binary, upgrade/upgrade-scripts/upgrade-container
At boot time, applications will fail to resolve the local hostname
to an IP address (i.e. the loopback address) until DNS servers are
reachable, and once they are reachable, such lookups will result in
external DNS requests, which is suboptimal given how often applications
resolve the local hostname. These lookups should all be done locally
without relying on external DNS servers.
When applications resolve a hostname to an IP address, they use the NSS
switch, which has a policy for how lookups should be done. On Delphix,
the hosts entry for /etc/nsswitch.conf looks like this:
```
hosts:          files dns mymachines
```
This means that any lookup will first consult local files (/etc/hosts),
and if that fails, will go out to DNS. The /etc/hosts file is managed
by cloud-init, and will …
=> DLPX-67355 [Backport of Issue DLPX-66957 to 6.0.0.0] hostname is not locally resolvable

live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary
This is a new requirement from Microsoft for the Azure marketplace. This creates an empty 1MB unallocated region at the beginning of the disk which Microsoft can use. 
Testing:
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2450/
We are deploying this image in the azure marketplace and have confirmed it has passed their certification.
=> DLPX-67392 azure marketplace requires a 1mb unallocated region

live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary
The change is to unblock a future change along the lines of https://github.com/delphix/appliance-build/pull/247.
The issue is that when we run the build outside of a container, there are mnt namespaces which are peers to the one in which the build is running. Currently, the following happens
- The root dataset `rpool/ROOT/delphix.v8IGiyn/root` is mounted on `/mnt/delphix.v8IGiyn`. This mount is propagated to the peer mnt namespaces.
- Child datasets `data`, `home`, and `log` are mounted beneath `/mnt/delphix.v8IGiyn`. These mounts are propagated to the peer mnt namespaces.
- The propagation type of `/mnt/delphix.v8IGiyn` is changed to 'slave'.
- We mount and unmount some other things which aren't directly relevant.
- We unmount  `data`, `home`, and `log`. These unmount events are _not_ …
=> Modify propagation type of root dataset mount before mounting children

upgrade/upgrade-scripts/common.sh
The following change is expected to ease debugging upgrade failures by increasing the logging.
Modern versions of bash include a BASH_XTRACEFD specifically for specifying an alternate file descriptor for the output of set -x. The following is used to redirect the verbose logging to the syslog file on the Delphix Engine. 
"""
exec 4> >(logger -t $0)
BASH_XTRACEFD="4"
"""
The following is used to add the source file & line number to the verbose output.
"""
PS4=':${BASH_SOURCE}:${LINENO}+' :
"""
Testing: git ab-pre-push --test-upgrade-from trunk: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2501/
=> DLPX-66981 Add verbose logging to the upgrade bash scripts

live-build/config/hooks/configuration/81-upgrade-repository.binary
This is a first stab at fixing https://github.com/delphix/appliance-build/issues/380.
Note that if we find that this works, for a more complete solution we would also need to apply this setting to live-build, however it is a bit more complicated so I want to test this out first since most of our failures are in `81-upgrade-repository.binary`.
I've tested the performance impact of disabling apt pipelining, and it is quite low for our use case. Downloading 643 packages (total of 356 MB) from our internal mirror takes 6.5 seconds instead of 5.5 with this change.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-pus …
=> Disable pipelining in apt when fetching packages

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
This change adds the "finalize" subcommand to the upgrade script, which
is intended to be used to clean up any filesystems, snapshots, etc. that
may have been generated during the upgrade process (e.g. for rollback).
This is intended to be used to mark the finalization or completion of
the upgrade, after which rollback will no longer be possible; e.g.
$ sudo /var/dlpx-update/latest/upgrade deferred
$ sudo /var/dlpx-update/latest/upgrade finalize
=> Add new "finalize" subcommand to upgrade script

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute
This change builds on the prior commit 9ba7066. Now, in addition to
logging the upgrade scripts' execution trace to syslog, we allow scripts
to log the stdout and stderr of their commands to syslog as well.
This new functionality is leveraged in the "execute" script, such that
we keep a better log of what "apt-get" is doing when it's upgrading
packages on the system.
=> Log upgrade scripts' stdout and stderr via syslog

live-build/config/hooks/configuration/10-disable-pipeline.chroot_early, live-build/config/hooks/configuration/81-upgrade-repository.binary, live-build/config/hooks/vm-artifacts/84-reset-apt-config.binary
This change supersedes https://github.com/delphix/appliance-build/pull/412.
It's been now a week since the we pushed the previous fix and we have not seen any failures on master related to downloading packages in `81-upgrade-repository.binary`. We did however see a few failures in the `lb_chroot_install-packages` step when installing `delphix-platform` and its dependencies.
This follow-up adds a conf file in `/etc/apt/apt.conf/` with this setting very early in the build. This makes sure that whenever apt is invoked within the image, it will always apply this setting. This includes:
- packages installed by live-build in `lb_chroot` (i.e. `delphix-platform` and its dependencies)
- packages installed through the various ansible roles in `80-build-configuration.binary`
- packages downloaded …
=> Disable apt pipelining for the whole duration of live-build

live-build/config/hooks/configuration/10-disable-pipeline.chroot_early, live-build/config/hooks/vm-artifacts/84-reset-apt-config.binary
Clean cherry-pick of https://github.com/delphix/appliance-build/pull/415
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2805/
=> [Backport to 6.0.1.0] Disable apt pipelining for the whole duration of live-build

live-build/config/hooks/configuration/10-disable-pipeline.chroot_early, live-build/config/hooks/vm-artifacts/84-reset-apt-config.binary
Clean cherry-pick of https://github.com/delphix/appliance-build/pull/415
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2806/
=> [Backport to 6.0.0.1] Disable apt pipelining for the whole duration of live-build

upgrade/upgrade-scripts/upgrade-container
This adds a new "shell" subcommand to the "upgrade-container" script,
which is intended to enable users to obtain an interactive shell session
within the specified container.
Currently, the "run" subcommand can be used, while specifying the shell
to run (e.g. /bin/bash), but since that does not specify the "--pty"
option with "systemd-run", the terminal may not work correctly (e.g.
keyboard input, pager output, etc).
Now, when folks want to obtain an interactive shell, they should use
this new "shell" subcommand, rather than "run".
=> Add "shell" subcommand to upgrade-container script

upgrade/upgrade-scripts/upgrade-container
This change fixes a regression introduced in acb60f4c. Without this
change, calling "upgrade-container stop" will return an error code, even
when the call successfully stops the container. With this change, when
the container is stopped successfully, we'll now properly return 0.
=> Fix "upgrade-container stop" return code on success

live-build/config/hooks/vm-artifacts/90-linux-migration-artifact.binary, live-build/misc/migration-scripts/dx_apply
- migration from 5.3.7.0: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2953/
- migration from 5.3.8.0: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2954/
- migration from 5.3.6.0 (should fail): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2952/
=> [Backport of DLPX-68628 to 6.0.1.0] Bump minimum version for migration to 5.3.7.0

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
- Tests for the changes have been added (for bug fixes / features)
_git-ab-pre-push_
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2977/console completed fine.
I cloned from the snapshot of the aws image and found that the snmptrapd pkg was available in the delphix VM when it came up. But it was inactive. I started the service and it came up fine with no errors.
```
delphix@ip-10-110-241-203:~$ sudo systemctl status  snmptrapd
● snmptrapd.service - Simple Network Management Protocol (SNMP) Trap Daemon.
Loaded: loaded (/lib/systemd/system/snmptrapd.service; disabled; vendor preset: enabled)
Active: inactive (dead)
delphix@ip-10-110-241-203:~$ sudo systemctl start …
```
=> QA-20893 Add the snmptrapd pkg to the delphix VM

upgrade/upgrade-scripts/rootfs-container
The "get_bootloader_devices" function attempts to list all devices
attached to "rpool" that are valid devices for storing the bootloader.
Since the devices used for "rpool" are partitions, it has to convert the
partion name (as returned by "zpool list") to the underlying device
name.
Unfortunately, the logic to do that mapping did not properly support
device partiations with "p" in the name; e.g. "nvme0n1p1" should map to
"nvme0n1", and "sda1" to "sda". This change updates this logic to better
support partitions names, regardless of it containing a "p" in the
partiation name, or not.
=> Incorrect handling for certain boot devices names

upgrade/upgrade-scripts/rootfs-container
The "get_bootloader_devices" function attempts to list all devices
attached to "rpool" that are valid devices for storing the bootloader.
Since the devices used for "rpool" are partitions, it has to convert the
partion name (as returned by "zpool list") to the underlying device
name.
Unfortunately, the logic to do that mapping did not properly support
device partiations with "p" in the name; e.g. "nvme0n1p1" should map to
"nvme0n1", and "sda1" to "sda". This change updates this logic to better
support partitions names, regardless of it containing a "p" in the
partiation name, or not.
=> DLPX-68848 [Backport of DLPX-68832 to 6.0.2.0] DFE during trunk to trunk deferred upgrade, Failed to set-bootfs for container 'delphix.AvZ8Xle'.

upgrade/upgrade-scripts/rootfs-container
When "/var/log" was moved to a seperate dataset in commit 76a37744, we
failed to properly adapt the "rootfs-container delete" script to account
for this change. Since then, the "rootfs-container delete" script has
likely been broken; currently, when I attempt to use this script, it
fails with the following error:
$ sudo /var/dlpx-update/latest/rootfs-container delete delphix.xfXCbRc
cannot destroy 'rpool/ROOT/delphix.xfXCbRc': filesystem has dependent clones
use '-R' to destroy the following datasets:
rpool/ROOT/delphix.iluoSLh/log
rootfs-container: 'zfs destroy -r rpool/ROOT/delphix.xfXCbRc' failed
The problem is, we're not properly handling the "log" dataset clones.
The fix is simple, we need to add the "log" dataset to the list of
datasets that we account for (i.e. the datasets that …
=> "rootfs-container delete" must process "log" dataset

upgrade/upgrade-scripts/rootfs-container
After performing a rollback of a failed not-in-place upgrade, if we remove
the container associated with that failure (i.e. the "new" container), we
will not remove the "container-delphix.XXXXXXX" snapshots used to generate
that new container, and these snapshots will persist indefinitely. This
change adds the necessary logic to the "rootfs-container delete" script to
remove these snapshots, after removing the container itself.
For example, without this change:
$ download-latest-image internal-dev
$ sudo unpack-image -x internal-dev.upgrade.tar
$ sudo /var/dlpx-update/latest/upgrade -v full
$ sudo /var/dlpx-update/latest/upgrade rollback
$ sudo /var/dlpx-update/latest/rootfs-container delete delphix.Bs4VTPo
$ sudo zfs list -t all -r rpool/ROOT/delphix.jDHoOtU
NAME …
=> Remove lingering snapshots after rollback event

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
The "verify_upgrade_not_in_progress" function only works correctly if
the "UPGRADE_TYPE" variable is not set prior to the function being
called. Unfortunately, in the two places we currently call that
function, that variable will have already been set.
This change fixes the issue by moving the calls to the function, such
that we call it prior to setting the variable. Additionally, we add a
check to the function to catch this error in usage earlier, and emit a
more appropriate error message.
Closes #461
=> Fix calls to "verify_upgrade_not_in_progress"

build.gradle, scripts/build-ancillary-repository.sh, scripts/build-upgrade-image.sh, scripts/common.sh, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/verify-jar, upgrade/verification-version.info.template, upgrade/version.info.template
DLPX-68919 Use New upgrade-verify.jar in appliance-build
DLPX-69031 Make sure that the delphix-verification package is not installed post upgrade
DLPX-64198 define and implement version info file for verification package
DLPX-68919: This PR adds in the new SUV based upgrade verify debian package as an input to the build-upgrade-image.sh script. This artifact is published to S3 from the https://gitlab.delphix.com/app/delphix-upgrade-verification repo and is intended to be packaged within the upgrade image for pre-upgrade verification.
DLPX-69031: This debian package is intended to be used only during pre-upgrade verification and hence is only installed for this purpose in verify-jar.sh and uninstalled once verification is completed.
DLPX-64198: The version of the upgrade verify artifact is …
=> Use "delphix-upgrade-verification" package in "verify-jar" script

build.gradle, scripts/build-ancillary-repository.sh, scripts/build-upgrade-image.sh, scripts/common.sh, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/verify-jar, upgrade/verification-version.info.template, upgrade/version.info.template
clean cherry-pick of https://github.com/delphix/appliance-build/pull/455
DLPX-69062 [Backport of DLPX-64198 to 6.0.2.0] define and implement version info file for verification package
DLPX-69063 [Backport of DLPX-68919] Use New upgrade-verify.jar in appliance-build
DLPX-69107 [Backport of DLPX-69031 to 6.0.2.0] Make sure that the delphix-verification package is not installed post upgrade
CLEAN git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3211/
CLEAN git ab-pre-push --test-upgrade-from 6.0.0.0 -a: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3212/
RUNNING git ab-pre-push --test-upgrade-from 6.0.1.0 -a: …
=> Backport of PR #455 to 6.0.2.0 (6.0/stage)

live-build/misc/ansible-roles/appliance-build.delphix-ldap/tasks/main.yml
This is my first pull-request to delphix Github repos so I'm sure I've messed something up, let me know and I will address it. 
https://jira.delphix.com/browse/TOOL-9008
When mounting LDAP user homes in the DCenter variant we have been seeing spurious issues due to mounting the pharos user homes over NFSv4. Seb has implemented this fix on scale-dc2 (DCoL system) to confirm that this works better. I talked to George and he was of the opinion that this this fix should also be extended to internal-dev variant. 
Modify /etc/auto.master to mount user homes with `vers=3`.
`git ab-pre-push -v "internal-dev internal-dcenter" -p esx`:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3141/console
=> TOOL-9008 LDAP user homes should be mounted using NFSv3

live-build/misc/ansible-roles/appliance-build.delphix-ldap/tasks/main.yml
Turns out this change is causing issues for user logging into internal-dev Delphix Engines via LDAP. One example of a workflow that has been broken is:
```
git au -m vm.dlpxdc.co
Updating: vm.dlpxdc.co
john.doe@vm.dlpxdc.co's password: 
```
This workflow has previously work with passwordless ssh as long as the user has their ssh keys in authorized_keys in the LDAP home directory. 
I have not clue why this works on scale-dc2 but not on internal-dev instances but I figure we should revert the change in https://github.com/delphix/appliance-build/commit/f84edf69cad73ebd653050e135877f11d5ec7855
and then investigate the issue.
=> Revert "TOOL-9008 LDAP user homes should be mounted using NFSv3 (#456)"

upgrade/upgrade-scripts/upgrade-container
http://reviews.delphix.com/r/58876/ changes how static DNS configuration is maintained. With this PR, we ensure that the static configuration file is persisted across not-in-place upgrades.
=> copy static DNS configuration for not-in-place upgrades

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
**Background**
Based on recent NFS latency investigations on DCoL, we found that having more `mountd` threads helps reduce the NFS latencies after the NFS caches are purged.  Each VM clone/destroy operation on DCoL is triggering a cache purge.
5 `mountd` threads seems to be the optimal count and adding more threads beyond 5 had a negative scaling effect.
**Testing**
We have already been running with 5 `mountd` threads on dcol1.
Built manually (i.e. `buildInternalDcenterKvm`) and tested that image
confirmed that the `nfs-kernel-server` config file had the expected `RPCMOUNTDOPTS`
confirmed that there were 5 `rpc.mountd` threads running
confirmed that there were 64 `nfsd` threads running
=> TOOL-9772 dcenter image should increase mountd thread count

scripts/build-upgrade-image.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
Currently, when we generate an upgrade image, we include the entire
contents of "\~/.aptly" in the image. It turns out, this causes us to
include two identical copies of each package, one under "\~/.aptly/pool"
and another under "\~/.aptly/public/pool".
For the upgrade image, we only need the contents of the "~/.aptly/public"
directory, so this change modifies the upgrade image generation logic,
as well as the upgrade image application logic, to take this into
account. As a result, this significantly reduces the size of the upgrade
image (roughly a 50% reduction in size).
=> Remove unnecessary files from upgrade payload

scripts/build-upgrade-image.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
Currently, when we generate an upgrade image, we include the entire
contents of "~/.aptly" in the image. It turns out, this causes us to
include two identical copies of each package, one under "~/.aptly/pool"
and another under "~/.aptly/public/pool".
For the upgrade image, we only need the contents of the "~/.aptly/public"
directory, so this change modifies the upgrade image generation logic,
as well as the upgrade image application logic, to take this into
account. As a result, this significantly reduces the size of the upgrade
image (roughly a 50% reduction in size).
=> Remove unnecessary files from upgrade payload (#472)

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
The projects/dx4linux branch in dcenter-gate is no longer used. All work is being done on master, and so that's the branch that needs to be checked out on deployed dcol instances.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3781/
=> Checkout the master branch instead of projects/dx4linux on dcol.

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
This is required for dcol1 which will track 6.0/stage and 6.0/release
=> backport tenacity requirement (part of TOOL-9418)

live-build/misc/ansible-roles/appliance-build.recovery-environment/meta/main.yml, live-build/misc/ansible-roles/appliance-build.recovery-environment/tasks/main.yml, live-build/variants/external-standard/ansible/playbook.yml, live-build/variants/internal-dev/ansible/playbook.yml
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3774/
We add a new role to install the recovery environment so that we can maintain a clearer dependency ordering between the recovery environment package and the app-stack; the recovery environment package currently relies on the app-stack, while the app-stack can function without the recovery environment.
=> Install recovery env

live-build/misc/migration-scripts/dx_apply
The root-cause of this bug is two-fold:
1. We have two locations for Grub configuration in 6.0.X. For fresh installs and upgrades, it lives in the delphix-platform repo. For migrations, it lives in this repo. The two must be kept in sync. It's easy to miss the latter.
2. We don't do performance testing on migrated engines; only on freshly installed ones.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3797/
I did a 5.3.9.0 to 6.0.3.0 migration using the image generated by this build, and verified that the `init_on_alloc` setting was correct post migration:
```
delphix@ip-10-110-242-36:~$ cat /proc/cmdline
root=ZFS=rpool/ROOT/delphix.9GQlImi/root console=tty0 console=ttyS0,115200n8 ipv6.disable=1 crashkernel=256M,high …
```
=> DLPX-71245 [Backport of DLPX-71244 to 6.0.3.0] fix for DLPX-69049 needs to also update grub for migrations

live-build/misc/migration-scripts/dx_apply
This is the sibling PR of https://github.com/delphix/delphix-platform/pull/243. This appliance-build change sets the grub menu for migrations, whereas the delphix-platform PR deals with fresh installs and upgrades.
ab-pre-push (includes migration testing): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3813/
=> DLPX-70914 [Backport of DLPX-70835 to 6.0.4.0] disable usb-storage device module loading in delphix 6.x (5.3 migration part)

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
remove the hotfix file post-upgrade.
ab-pre-push : http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3831/
Testing : tested deferred upgrade of an engine with a non-empty hotfix file using upgrade image from above build. The hotfix file was removed post-upgrade.
=> DLPX-69447 Fixed hotfixes should be removed from /etc/hotfix during upgrade application

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
clean cherry-pick of https://github.com/delphix/appliance-build/pull/482
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3839/
=> DLPX-71311 [Backport of DLPX-69447 to 6.0.4.0] Fixed hotfixes should be removed from /etc/hotfix during upgrade application

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Related to [TOOL-9835](https://jira.delphix.com/browse/TOOL-9835) to add linting to dcenter-gate, Python's `six` module is being added as a dependency. Currently `six` is already installed on original DCenter, DCoL1, DCoL2, and scale-dc2, but to ensure this module is imported in future DCenter builds I would like to add `six` as part of the Ansible role.
=> Related to TOOL-9835: Add py-six to DCenter appliance-build ansible role

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Updates the DCenter Python package list to adapt to recent changes in `dcenter-gate` and prepare for future work to migrate to Python 3 and pyVmomi.
- Add `python-dbg` and `python-dev` for use with GDB.
- Remove `python-requests`, since we no longer depend on it as of TOOL-9913.
- Add `python-pyvmomi`, because we eventually plan to migrate from PySphere to pyVmomi. Installing the package now enables us to begin preliminary testing with pyVmomi.
- Add `python-virtualenv`, because we eventually plan to deploy our dependencies in a virtual environment. Installing the package now enables us to begin preliminary testing of virtual environments.
- Add Python 3 versions of all Python 2 packages, because we eventually plan to migrate from Python 2 to Python 3. Installing Python 3 now enables us …
=> Update DCenter Python package list

upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade
The "verify_upgrade_not_in_progress" function only works correctly if
the "UPGRADE_TYPE" variable is not set prior to the function being
called. Unfortunately, in the two places we currently call that
function, that variable will have already been set.
This change fixes the issue by moving the calls to the function, such
that we call it prior to setting the variable. Additionally, we add a
check to the function to catch this error in usage earlier, and emit a
more appropriate error message.
Closes #461
=> Fix calls to "verify_upgrade_not_in_progress" (#462)

upgrade/upgrade-scripts/upgrade-container
This change fixes a regression introduced in acb60f4c. Without this
change, calling "upgrade-container stop" will return an error code, even
when the call successfully stops the container. With this change, when
the container is stopped successfully, we'll now properly return 0.
=> Fix "upgrade-container stop" return code on success (#433)

live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
HeadlessChrome cannot be started, thus `ui-precommit` runs are failing.
Issue Number: DLPX-71833
We use `apt-get install chromium-browser` to install Chromium and its dependencies, so when running the UI unit tests, Puppeteer can start the headless chrome.
But in the new version of chromium-browser, `apt-get install chromium-browser` doesn't install all necessary dependencies. libXss.so.1 is missing. So the headless chrome cannot be started.
The fix is to manually add libXss.so.1 to the list of `apt-get install` to make sure it is installed.
This build shows with this fix, headless chrome can be started to run the tests. …
=> DLPX-71833 ui-precommit fails to start ChromeHeadless

live-build/build.gradle, scripts/build-ancillary-repository.sh, scripts/common.sh
This is the main linux-pkg commit in the linux-pkg rework project (TOOL-9778).
**See [design document](https://docs.google.com/document/d/1wD5VZGhTLac7xzKZSJyKkJq72ailorCivJwppP0tkWQ) for more information.** 
The summary is that the new `combine-packages` job will gather the artifacts for all the packages except upgrade-verification into a single S3 location, which will now be consumed by appliance-build.
See [work plan](https://docs.google.com/document/d/1wD5VZGhTLac7xzKZSJyKkJq72ailorCivJwppP0tkWQ/edit#heading=h.st5bs7ygy0q6) for info on dependencies on PRs in other repositories.
See [test worksheet](https://docs.google.com/spreadsheets/d/1PXy6vk92tnhI9B1FHTrR1Ay7YR2_qVRyga46WYKfwwQ)
=> TOOL-10160 linux-pkg rework: main appliance-build change

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Clean backports of #485 and #488 to `6.0/release`.
=> Backports of Python package changes

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Amends #488. Updates the DCenter package list to improve debuggability, adapt to recent changes in `dcenter-gate`, and prepare for future work.
- Adding debug symbols via `nfs-common-dbgsym` and `nfs-kernel-server-dbgsym` to improve debuggability.
- Removing `python3-paramiko`, as it is no longer needed when running `dcenter-gate` with pyVmomi. Note that Paramiko must remain installed for Python 2 until we drop support for PySphere (scheduled for later this month).
- Removing `virtualenv` in favor of `venv` as in [QI-1699](https://jira.delphix.com/browse/QI-1699). Note that we do not currently use a virtual environment, but we plan to start using one in future packaging and deployment work. We will likely be Python 3 only by the time that work is begun, so it makes more sense to use the …
=> DCenter package updates

live-build/build.gradle, scripts/build-ancillary-repository.sh, scripts/common.sh
This is a clean backport of #490 to get the linux-pkg rework on 6.0/stage and 6.0/release. Once this lands on 6.0/stage I'll merge this change into 6.0/release.
This change will have to be pushed along with a bunch of other changes. See the [work plan](https://docs.google.com/document/d/1wD5VZGhTLac7xzKZSJyKkJq72ailorCivJwppP0tkWQ/edit#heading=h.20tnd5kqm8eg) for more info.
See https://docs.google.com/document/d/1wD5VZGhTLac7xzKZSJyKkJq72ailorCivJwppP0tkWQ/edit#heading=h.czqhgs5qmlfa
=> TOOL-10595 [Backport of TOOL-10160 to 6.0.6.0] linux-pkg rework: main appliance-build change

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
I've downloaded the original livecd-rootfs package, manually applied the patch (attached in JIRA) and repackaged the package.
An alternative approach would be to patch the installed package after its installation (see https://github.com/pzakha/appliance-build/commit/99c88ca4121e3c6f3d44e56a6edba6dffb1cf034). However the patch could fail to apply in the future if Ubuntu was to update the package with some changes in that file.
We will need to create a bug in JIRA to remember to revert back to the default Ubuntu package once that patch is integrated upstream and pulled into bionic. This bug is being tracked upstream by https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1893898.
Without this fix, Guest OS Customizations cannot be applied when cloning this OVA as ESX thinks that …
=> DLPX-72869 Patch VMDK generation tool to mark that the vmdk contains a vmtools install

.github/scripts/install-ansible-lint.sh, .github/workflows/main.yml
The Github Action "::set-env" command is no longer supported and results
in failures when it is used. This change updates our scripts to remove
the usage of that command, and use the "GITHUB_ENV" interface instead.
=> Github Action "::set-env" is no longer supported

.github/scripts/install-ansible-lint.sh, .github/workflows/main.yml
The Github Action "::set-env" command is no longer supported and results
in failures when it is used. This change updates our scripts to remove
the usage of that command, and use the "GITHUB_ENV" interface instead.
Closes #495
=> Github Action "::set-env" is no longer supported (#501)

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
As of TOOL-10692, this is dead code and can be deleted.
=> Remove dangling references to dcenter.conf

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
Clean cherry-pick of https://github.com/delphix/appliance-build/pull/497
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4384/
=> DLPX-73044 [Backport of DLPX-72860 to 6.0.6.0] Patch VMDK generation tool to mark that the vmdk contains a vmtools install

live-build/config/hooks/vm-artifacts/template.ovf
This PR instructs VMWare that the Delphix Engine can handle memory and CPU hot-add. It has been tested in conjunction with the associated zfs and app-stack changes, and behaved correctly.
=> Enable hot-add

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Backports of #494 and #503 to `6.0/release` in preparation for the next scheduled upgrade of our production systems.
Repeated the testing from the original changes.
`git ab-pre-push`: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4486/consoleFull
Booted the image and ran various tests to ensure the changes were present:
```
$ dpkg -L nfs-common-dbgsym
/.
/usr
/usr/lib
/usr/lib/debug
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/0c
/usr/lib/debug/.build-id/0c/2167c30e99c1bc229ce3618e77f7e650706104.debug
/usr/lib/debug/.build-id/10
/usr/lib/debug/.build-id/10/487e7dc455dd86b267a1a12625fc6b63fb032e.debug
/usr/lib/debug/.build-id/1a
/usr/lib/debug/.build-id/1a/14ab844da9900ecde197db5daa998818f58652.debug …
```
=> Backports of DCenter package updates

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
The builds are failing right now because of this patch. It looks like Canonical has provided a newer package, and the apt installer from ansible is not happy that we are asking it to install an earlier version. The good news is that the newer package they released seems to have the fix we applied in the patch (a similar version of it), so we should be able to just revert DLPX-72860.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4497/
- TODO: verify that the new package actually fixes the original problem.
=> Revert "DLPX-72869 Patch VMDK generation tool to mark that the vmdk contains a vmtools install"

bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
Same as #511 but for 6.0/stage
- ab-pre-push (esx): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4503/
=> Revert "DLPX-73044 [Backport of DLPX-72860 to 6.0.6.0] Patch VMDK generation tool to mark that the vmdk contains a vmtools install"

build.gradle, live-build/build.gradle, scripts/aptly-repo-from-debs.sh, scripts/build-ancillary-repository.sh, scripts/common.sh
This is a follow-up to http://reviews.delphix.com/r/64085/, which adds the upgrade-verify package to the combine-packages bundle.
Fixes #509
Must be pushed after http://reviews.delphix.com/r/64085/
- See comments in https://jira.delphix.com/browse/TOOL-10766 for the testing that was done
- Manually tested that this fixes issue #509
=> DLPX-73299 appliance-build: Fetch upgrade-verify package from combined-packages bundle

build.gradle, live-build/build.gradle, scripts/aptly-repo-from-debs.sh, scripts/build-ancillary-repository.sh, scripts/common.sh
Clean backport of #510 
This depends on #514
Note that I will rebase this work once #514 is pushed so that it will only contain one commit.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4521/
=> DLPX-73378 [Backport of DLPX-73299 to 6.0.6.0] appliance-build: Fetch upgrade-verify package from combined-packages bundle

live-build/config/hooks/vm-artifacts/template.ovf
This updates our default builds to use pvscsi and change our VM compatibility to version 11.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4603/
=>  CP-4451 Bump OVA hardware version to HWv11 and CP-4449 pvscsi on by default

upgrade/upgrade-scripts/execute
Currently when applying a hotfix image generated by the new hotfix
workflow being developed in CP-4190, nothing will happen when the
upgrade is attempted. This is due to the "delphix-entire" package in the
hotfix being installed, matching the version of the package that's
already installed. Thus, the package manager chooses not to install the
new packagecontained in the upgrade/hotfix image, since it thinks the
same package is already installed, due to the two having the same
version.
We need to adapt the "execute" script that's used during upgrade, such
that we always install the new "delphix-entire" package contained in the
upgrade/hotfix image, even if the package versions are identical.
=> DLPX-74045 adapt upgrade "execute" script to better handle new hotfix workflow

live-build/config/hooks/vm-artifacts/template.ovf
Clean cherry-pick
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4710/
=> CP-4470 [Backport of CP-4449 to 6.0.7.0] use pvscsi by default and CP-4471 [Backport of CP-4451 to 6.0.7.0] Bump OVA hardware version to HWv11

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Amends #523. In that change, we stopped installing Python 2 but neglected to also stop installing PySphere with the Python 2 version of `pip`. We no longer use PySphere, so we can stop installing it as well.
=> Stop installing PySphere

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
See [TOOL-10813](https://jira.delphix.com/browse/TOOL-10813).
=> TOOL-10813 appliance-build unnecessarily sets preserve_hostname: true

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
These service units are unused (we have our own service unit for DHCP and DNS) and perpetually in the failed state:
```
$ systemctl list-units --failed
UNIT                     LOAD   ACTIVE SUB    DESCRIPTION                                                                                                                                                                          
● isc-dhcp-server.service  loaded failed failed ISC DHCP IPv4 server                                                                                                                                                                 
● isc-dhcp-server6.service loaded failed failed ISC DHCP IPv6 server …
```
=> Disable default DHCP service units

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Omnibus backport of #523, #524, #525, and #526 to `6.0/stage`. As of this change, `live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml` is identical on `master` and `6.0/stage`.
=> Backport of #523, #524, #525, and #526 to 6.0/stage

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Omnibus backport of #523, #524, #525, and #526 to `6.0/release`. As of this change, `live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml` is identical on `master`, `6.0/stage`, and `6.0/release`.
=> Backport of #523, #524, #525, and #526 to 6.0/release

live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
clean cherry-pick of https://github.com/delphix/appliance-build/pull/489
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4883/
=> DLPX-71882 [Backport of DLPX-71833 to 6.0.8.0] ui-precommit fails to start ChromeHeadless

build.gradle, live-build/build.gradle, live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary, scripts/upgrade-image-from-aptly-repo.sh, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container, upgrade/version.info.template
Backport of #507. Clean cherry pick. 
[Testing](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4895/console)
=> Initial changes to support new hotfix workflow(s) (#507)

upgrade/upgrade-scripts/upgrade-container
```
~$ sudo cat /etc/iscsi/initiatorname.iscsi
InitiatorName=iqn.2021-09.org.serapheim:01:42a11723a8fb
~$ sudo tree /etc/iscsi/nodes/
/etc/iscsi/nodes/
└── iqn.2021-03.bogus.com
└── bogus.com,3260
1 directory, 1 file
~$ download-latest-image
download: s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/latest to ./latest
download: s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/4997/upgrade-artifacts/internal-dev.upgrade.tar to ./internal-dev.upgrade.tar
~$ ls internal-dev.upgrade.tar
internal-dev.upgrade.tar
~$ sudo unpack-image -x internal-dev.upgrade.tar
Progress increment: 15:17:21:422147680+0000, 10, Extracting upgrade image.
Progress increment: 15:20:03:362647124+0000, 40, Verifying format. …
```
=> DLPX-73923 Persist iSCSI initiator files during not-in-place upgrade

upgrade/upgrade-scripts/upgrade
Problem : The properties in upgrade.properties gets cleared in a finally block in StackStartup.java whereas the finalize() function is invoked asynchronously in the context of a job. The properties cannot be expected to still be present in the finalize() function.
Solution : The finalize() function is only called in the context of post-upgrade, so it does not need to check the upgrade.properties once again. The file itself gets cleaned up by the finalize() function during the removal of the entire unpack directory, so the risk of a re-execution is minimal. Even if re-executed, there does not seem to be any detrimental effects of the statements that are presently in the finalize() function.
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-buil …
=> DLPX-75229 finalize() should not rely on properties in upgrade.properties

upgrade/upgrade-scripts/upgrade
Clean cherry-pick of https://github.com/delphix/appliance-build/pull/538
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5038/
=> DLPX-75232 [Backport of DLPX-75229 to 6.0.8.0] finalize() should not rely on properties in upgrade.properties

scripts/aptly-repo-from-image-diff.sh
Currently, if we generate an upgrade image diff from two images that
have the same delphix-entire package version, the resultant Aptly
repository will not contain any delphix-entire package in it. This is
problematic when that Aptly repository is later used with the script
used to generate an upgrade image from that repository, as the script
requires the repository to contain a "delphix-entire" package in it.
Thus, to avoid this issue, this change modifies the image diff logic to
ensure we never remove the "delphix-entire" package.
=> Don't remove "delphix-entire" when generating image diffs

upgrade/upgrade-scripts/upgrade-container
https://github.com/delphix/appliance-build/pull/532
```
delphix@sd-60-upgrade:~$ sudo tail -n 1 /etc/iscsi/initiatorname.iscsi
InitiatorName=iqn.1993-08.org.debian:01:58d010e548ec
delphix@sd-60-upgrade:~$ sudo tree /etc/iscsi/nodes/
/etc/iscsi/nodes/
└── iqn.2021-03.bogus.com
└── bogus.com,3260
1 directory, 1 file
delphix@sd-60-upgrade:~$ download-latest-image
download: s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/latest to ./latest
download: s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/5189/upgrade-artifacts/internal-dev.upgrade.tar to ./internal-dev.upgrade.tar
delphix@sd-60-upgrade:~$ ls internal-dev.upgrade.tar
internal-dev.upgrade.tar
delphix@sd-60-upgrade:~$ sudo unpack-image -x …
```
=> DLPX-75258 [Backport of DLPX-73923 to 6.0.9.0] Persist iSCSI initiator files during not-in-place upgrade

live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
In support of the Object Storage project, we should install the rust devtools on development engines.
While the recommended way to install rust is using rustup, we use the ubuntu packaged version of rust for a more repeatable build process with fewer external dependencies. However, [these packages do not update frequently](https://answers.launchpad.net/ubuntu/+source/rustc/+question/696726). If in the future we find that we need to use more up-to-date versions of the rust compiler, we can either switch to using rustup, or build our own linux-pkg off of the stable rust releases.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5108/console
=> Add rust to dev environment

upgrade/prepare, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/upgrade, upgrade/upgrade-scripts/verify-jar
DLPX-75122 Use delphix version and hotfix in version.info in verify-jar script
DLPX-75091 Make upgrade image prepare script hotfix aware
The hotfix id needs to be passed into delphix-upgrade-verification/SUV so that SUV may operate on the correct version. Only works with corresponding [SUV changes](http://reviews.delphix.com/r/68590), otherwise verification will fail when an older SUV is given the hotfix value and does not know what to do with it.
Also refactored how version is determined. Instead of relying on a value in the filesytem path, the version is entirely sourced from version.info (and literally sourced via bash, pun intended). 
Tested with upgrade images and hotfix images with the corresponding SUV changes.
=> DLPX-75091 DLPX-75122 Make upgrade image prepare script hotfix aware

upgrade/upgrade-scripts/upgrade
This reverts commit 46ad55ca4d39866efd98d0bcef5e889a30647e28.
=> Revert "DLPX-75576 disable upgrade verification for hotfixes applied via upgrade-scripts (#546)"

upgrade/upgrade-scripts/upgrade
This reverts commit 26c960f1697c1cef7d66bae8326670094b9e206d.
=> Revert "DLPX-75578 [Backport of DLPX-75576 to 6.0.9.0] disable upgrade verification for hotfixes applied via upgrade-scripts (#547)"

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
Context
The Uncomplicated Firewall (ufw) utility is a frontend for iptables which is well-suited for host-based firewalls. `ufw` aims to provide an easy to use interface for those unfamiliar with firewall concepts, while at the same time simplifying iptables commands to help an admin who knows what he or she is doing.
Problem
The AppData team wants to add testing around the docker plugin runtime without internet access. The build should target internal qa and dev builds, but should be excluded from customer engines.
Solution
The ufw utility should allow us to configure the engine to allow outgoing connections to SSH, DNS and specific source and target host environments while also restricting internet access elsewhere.
Testing
git ab-pre-push: …
=> CP-5334 Add ufw package to appliance-build

upgrade/upgrade-scripts/upgrade
In commit e7dd85e2 we introduced the `get_hotfix_version` function for
obtaining the hotfix version of the currently running root filesystem.
The problem is that in c4357a4e we added logic that intended to use this
function, but instead tries to call the `get_current_hotfix` function,
which doesn't exist. This leads us to never retreiving the hotfix
version correctly via the `rollback` subcommand of the `upgrade` script.
=> DLPX-76328 upgrade script obtains hotfix version incorrectly

upgrade/upgrade-scripts/upgrade
In commit e7dd85e2 we introduced the `get_hotfix_version` function for
obtaining the hotfix version of the currently running root filesystem.
The problem is that in c4357a4e we added logic that intended to use this
function, but instead tries to call the `get_current_hotfix` function,
which doesn't exist. This leads us to never retreiving the hotfix
version correctly via the `rollback` subcommand of the `upgrade` script.
=> DLPX-76329 [Backport of DLPX-76328 to 6.0.9.0] upgrade script obtains hotfix version incorrectly

upgrade/upgrade-scripts/execute
Currently when applying a hotfix image generated by the new hotfix
workflow being developed in CP-4190, nothing will happen when the
upgrade is attempted. This is due to the "delphix-entire" package in the
hotfix being installed, matching the version of the package that's
already installed. Thus, the package manager chooses not to install the
new packagecontained in the upgrade/hotfix image, since it thinks the
same package is already installed, due to the two having the same
version.
We need to adapt the "execute" script that's used during upgrade, such
that we always install the new "delphix-entire" package contained in the
upgrade/hotfix image, even if the package versions are identical.
=> DLPX-74045 adapt upgrade "execute" script to better handle new hotfix workflow (#520)

scripts/upgrade-image-from-aptly-repo.sh
This change adds logic to cause a failure when certain environment
variables are missing, and the build is being run via Jenkins.
When environment variables are missing, we currently will provide
default values, such that the build doesn't fail. These default values
generally are not sufficient for anything besides allowing the build to
complete (e.g. the resultant upgrade images may fail upgrade). Further,
the main motivation for generating these default values, is to make it
easier to run the build manually, and aid developer iteration.
Thus, when it's clear that the build is being run via Jenkins, where
these missing environment variables more likely point to an error or
broken automation, than an intentional omission of these variables, it's
better to report the error than set and use …
=> TOOL-11824 Harden against mistakes when running via Jenkins

scripts/upgrade-image-from-aptly-repo.sh
This change adds logic to cause a failure when certain environment
variables are missing, and the build is being run via Jenkins.
When environment variables are missing, we currently will provide
default values, such that the build doesn't fail. These default values
generally are not sufficient for anything besides allowing the build to
complete (e.g. the resultant upgrade images may fail upgrade). Further,
the main motivation for generating these default values, is to make it
easier to run the build manually, and aid developer iteration.
Thus, when it's clear that the build is being run via Jenkins, where
these missing environment variables more likely point to an error or
broken automation, than an intentional omission of these variables, it's
better to report the error than set and use …
=> TOOL-11824 Harden against mistakes when running via Jenkins (#569)

live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
Backporting to 6.0/stage:
```
commit 923aa1320dc6963ef6c3b3da0cc466f2b03018b7
Author: Paul Dagnelie <paul.dagnelie@delphix.com>
Date:   Fri Apr 23 14:36:08 2021 -0700
Add rust to dev environment (#544)
```
appliance-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5787/console
=> Add rust to dev environment (#544)

live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
When testing changes to the front end blackbox ends up running `ant all` on a Delphix Engine (instead of `ant dev`), and that not only rebuilds the front end but also the Delphix Connector. To build the connector, the build installs a bunch of package dependencies from artifactory; and one of those package dependencies depends on another Ubuntu package, `pkg-config`, which is not present on the engine.
As it happens, `pkg-config` was already added on internal-dev engines on master by an unrelated change, #577, but that change was not yet backported to 6.0/stage when this failure happened. Given that #577 relates to zfs development and pkg-config is also needed for virtualization development, it seems appropriate to add it explicitly here.
- Ideally we would move the Delphix Connector to a …
=> DLPX-76694 Failure to build DelphixConnector on Delphix Engine, causing gui_sanity testing to fail

upgrade/upgrade-scripts/rootfs-container
Clean backport of the bug on master
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5803/ test failure appears unrelated
=> DLPX-76770 [Backport of DLPX-68846] logic for determining device path for grub operations during upgrade is fragile

live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
Clean cherry-pick of #578 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5808/
=> DLPX-76769 [Backport of DLPX-76694 to 6.0.10.0] Failure to build DelphixConnector on Delphix Engine, causing gui_sanity testing to fail

.github/scripts/install-ansible-lint.sh
`check-ansible` is failing because `install-ansible-lint` is failing with:
```
HEAD is now at 5d5ff0b Update version to 3.4.21
+ git branch -D master
error: branch 'master' not found.
Error: Process completed with exit code 1.
```
See https://github.com/delphix/appliance-build/pull/586/checks?check_run_id=3265249798
=> install-ansible-lint is failing

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml, live-build/variants/internal-dcenter/package-lists/dcenter.list.chroot, scripts/run-live-build.sh
Supersedes #576. Closes #582. Introduces support for variant-specific package lists in `live-build/variants/${APPLIANCE_VARIANT}/package-lists`, updating `scripts/run-live-build.sh` to merge them with the existing package lists that apply to all variants before plumbing through the result to `live-build(7)`. This allows us to move the list of packages for the `internal-dcenter` variant from the `appliance-build.dcenter` Ansible role to a new `dcenter.list.chroot` package list, which contains all of the original packages as well as `openjdk-11-jdk-headless`. These packages are installed in a context where `/proc` is mounted, which is necessary for `ca-certificates-java` (a dependency of `openjdk-11-jdk-headless`). We continue to use Java 8 as the default Java runtime to allow us to …
=> Want variant-specific package lists for `live-build(7)`

upgrade/upgrade-scripts/execute
Note that although this bug could affect any version it was found when doing upgrade to Ubuntu 20.04 on branch focal (See CP-3955)
The logic introduced in DLPX-66313 via https://github.com/delphix/appliance-build/pull/425 ends up deleting configuration files that should not be deleted.
The original intent of that logic was to delete unwanted configuration files (files in /etc) that were removed in a newer version of a package. However there is an issue for configuration files that were previously provided by one package but are now provided by another package, as those are also removed by that logic.
Here's an example.
The following system was upgraded from master (18.04) to focal (20.04):
```
$ dpkg-query -Wf '${Conffiles}\n' >/var/tmp/conffiles
$ cat /var/tmp/conffiles | grep obsolete | …
```
=> DLPX-76907 obsolete conf file cleanup logic incorrectly removes conf files that were moved to another package

upgrade/upgrade-scripts/upgrade-container
It has been observed that simply starting the verification container enables ip forwarding on the host (and in turn disables LRO). This seems to persist post a DEFERRED upgrade, leading to potential performance regression in networking. Having attempted to prevent the container from setting ip forwarding to true at all (see PR https://github.com/delphix/delphix-platform/pull/314) and hit an issue when the upgrade needs to install a new version of systemd (see jira for more info on this), this PR attempts to leave the container properties as is, while attempting to reset the networking state post-verification. This is a relatively short window in which LRO gets disabled and should be tolerable.
The relevant properties can be viewed on the engine using below commands :
sudo sysctl …
=> DLPX-76802 Starting Verification container enables IP forwarding on host

upgrade/upgrade-scripts/upgrade-container
Clean cherry-pick of https://github.com/delphix/appliance-build/pull/584
git ab-pre-push : http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5927/
=> DLPX-76893 [Backport of DLPX-76802 to 6.0.10.0] Starting Verification container enables IP forwarding on host

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
This work should be integrated after DLPX-76874 (https://github.com/delphix/delphix-platform/pull/323), which will have ntp installed on the internal-dcenter variant, but in a disabled state.
There are 2 different time daemons available on Ubuntu: systemd-timesyncd and ntp, which are exclusive.
On Ubuntu 18.04 systemd-timesyncd.service is installed by default with the systemd package. Installing ntp does not prevent systemd-timesyncd.service from running, and so this fix is not required. systemd-timesyncd.service would start first, which will prevent ntp.service from later starting whether it is enabled or not. Therefore on Ubuntu 18.04 systemd-timesyncd will be syncing the time on the internal-dcenter variant regardless.
However, on Ubuntu 20.04 systemd-timesyncd.service is provided by a …
=> TOOL-12005 Enable ntp on dcenter-internal variant

live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
Note, we still need to land this first: https://github.com/delphix/linux-pkg/pull/188
=> Use "delphix-rust" instead of Ubuntu's Rust packages

live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
To facilitate development for SSO and OAuth2, we want to define DLPX_DEBUG for the SSO app in development engines, just like we do for the management stack, in the same way as we do for the stack -- by adding a systemd configuration override to the development variant.
ab-pre-push with tests: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6089/
=> CP-5946 Enable Java debug mode for sso app

live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
The main idea behind this change is to make it easier to control which services get to run and which services should not run. In short, the solution is to mask services instead of just disabling them when we want them to not run, and then unmask them when we want them to run again.
This work is split up into 3 reviews which must all be pushed together. The 2 other PRs are:
- dlpx-app-gate: http://reviews.delphix.com/r/74397/
- delphix-platform: https://github.com/delphix/delphix-platform/pull/333
This addresses the following issues:
1. Some services that we want to never run end up getting re-enabled when some packages are upgraded / re-installed.
2. Other services that we want to be disabled / enabled conditionally end up in the wrong state after / during an upgrade.
One of the reasons …
=> DLPX-77901 Prevent services from being re-enabled on upgrade

live-build/auto/config, live-build/config/archives/delphix-secondary-mirror.list.in, live-build/config/archives/localhost.list, live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml, scripts/aptly-repo-from-debs.sh, scripts/aptly-repo-from-image-diff.sh, scripts/build-ancillary-repository.sh, scripts/run-live-build.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
Note: this will only be integrated when transitioning master to Ubuntu 20.04.
Here's a summary of the changes:
- Update live-build distribution from bionic to focal
- Update the distribution of our upgrade images from bionic to focal (note that I don't believe that the name we use there matters at all and that we could simply use "delphix" as the distribution, that said it's something to be tested out)
- Update the secondary mirrors distribution list
- Remove mentions of `systemd-timesyncd.service` since that service is not installed on 20.04
- This code has been soaking on focal for a few months.
- Note that I've reverted focal commit https://github.com/delphix/appliance-build/commit/b142de40b9b741158e9049eb7ec938fc66ac5911 which I don't think is necessary now that DLPX-77901 has been …
=> TOOL-12369 appliance-build: changes for Ubuntu 20.04

live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
See comment in the code for a bit more context on the description.
I've considered an alternative which is to use a 3rd party PPA to get a chromium package with all the dependencies pulled implicitly, but for security reasons we do not want to use 3rd party PPAs unless strictly necessary.
See https://github.com/pzakha/appliance-build/commit/f847b624cb1c1d53da57ee6ae1a84309350c7956 for the alternative approach.
- ab-pre-push for creating internal-testing variant: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6506/ (pass)
- UI-precommit on tip master: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/integration-tests/job/ui-precommit/job/pre-push/1774/console (failed due to a suspected recent regression on …
=> DLPX-78255 ui-precommit fails due to missing Chrome dependency libnss3.so

live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
Note that this will also require a change in devops-gate to pass GITHUB_TOKEN, until then the zfs repo will not be fetched on internal-dev VMs.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6524/
- ab-pre-push, with devops changes to pass GITHUB_TOKEN to build: http://collins.d.delphix.com:21968/job/devops-gate/job/master/job/appliance-build/job/master/job/pre-push/104/
=> TOOL-12434 Need to use devops-bot token to fetch some repositories during appliance-build

gradle/wrapper/gradle-wrapper.properties, live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary, live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.masking-development/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml, live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml, live-build/variants/internal-dcenter/package-lists/dcenter.list.chroot, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
This backports a bunch of commits from master to 6.0/stage.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6528/
- manually test that app-data testing on 6.0/stage still works with TOOL-12368
=> Backports to 6.0/stage

live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
This backports #615
As for the original, it has dependencies on 2 other reviews:
dlpx-app-gate: http://reviews.delphix.com/r/75270/
delphix-platform: https://github.com/delphix/delphix-platform/pull/338
- ab-pre-push, including work from the other repos: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6535/
- build internal-dcenter: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6537/
=> DLPX-78304 [Backport of DLPX-77901 to 6.0.12.0] Prevent services from being re-enabled on upgrade

upgrade/upgrade-scripts/upgrade-container
This failure only happens during master -> master upgrades. It looks like in Ubuntu 20.04 `systemd-nspawn` got some permissions clamped down.
- ab-pre-push (upgrade from master): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6540/ (PASS)
- ab-pre-push (upgrade from 6.0/stage): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6541/ (Unrelated failure: DLPX-72032)
=> DLPX-78275 Upgrade-verification is failing because /sys/module is not available in container

upgrade/upgrade-scripts/upgrade-container
Clean cherry-pick of #628
Note that this work will only be required for when we transition 6.0/stage to Ubuntu 20.04, however it should not regress anything on Ubuntu 18.04.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6556/
=> DLPX-78328 [Backport of DLPX-78275 to 6.0.12.0] Upgrade-verification is failing because /sys/module is not available in container

live-build/config/hooks/configuration/81-upgrade-repository.binary
Manually running the appliance-build steps mentioned in the README file of the repo fails with the following error:
```
./config/hooks/81-upgrade-repository.binary: line 86: AWS_S3_HOTFIX_METADATA: unbound variable
E: config/hooks/81-upgrade-repository.binary failed (exit non-zero). You should check for errors.
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
+ kill -9 104400
+ [[ ! -f binary/SHA256SUMS ]]
+ exit 1
> Task :live-build:buildInternalDevAws FAILED
```
The problem was introduced by :
```
commit e6c2dd1c29afae49778ab470fcb9bc62524842ac
Author: Matt Skinner <matt.skinner@delphix.com>
Date:   Mon Aug 9 12:13:58 2021 -0400
DLPX-76293 Copy Hotfix Metadata Generation to appliance-build (#574)
``` …
=> DLPX-78464 Regression in appliance-build from DLPX-76293

upgrade/upgrade-scripts/execute
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6569/
- tested manual upgrade from 6.0.11.0 -> trunk using external-standard variant
=> DRAFT: DLPX-78371 Upgrade fails because some packages are unexpectedly autoremoved by apt

scripts/aptly-repo-from-debs.sh, scripts/build-ancillary-repository.sh
As part of http://reviews.delphix.com/r/75405/ we are removing devops-gate/master from the job
hierarchy on Jenkins. Need to update all the references.
Remove the references.
Ran appliance-build-pre-push using my developer Jenkins controller
http://selfservice.jtor-docker.dcol2.delphix.com/job/appliance-build-orchestrator-pre-push/2/console
This needs to be merged after the new Jenkins controllers have been deployed. Otherwise, jobs would fail to fetch the right artifacts on S3 since the JOB_NAME will differ.
=> TOOL-12471 Remove Jenkins job references to devops-gate/master in appliance-build

scripts/aptly-repo-from-debs.sh, scripts/build-ancillary-repository.sh
Clean cherrypick of: https://www.github.com/delphix/appliance-build/pull/633
=> TOOL-12541 [Backport of TOOL-12471 to 6.0.12.0] Remove Jenkins job references to devops-gate/master in appliance-build

live-build/config/archives/delphix-secondary-mirror.list.in, live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
appliance-build needs to be updated to
1) pickup the standard ubuntu package from the contrib PPA in our linux-package-mirror
2) mask the td-agent service.
This is a companion of [app-gate](CP-6651) and [linux-pkg](CP-5327) changes. 
Testing:
[ab-pre-push](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6632/)
=> CP-6676 appliance-build changes to simplify the fluentd build

upgrade/upgrade-scripts/execute
We've discovered that "apt-get autoremove" does not work for our needs.
Specifically, packages may erroneously remain installed due to suggested
and recommended package dependencies, as well as due to virtual package
dependencies. While we could alleviate the issue w.r.t. suggested and
recommended dependencies via configuration changes, there isn't a clear
way to resolve the issue for virtual packages. Thus, the solution
adopted in this change is to simply not use "apt-get automoremove"
anymore, and instead, explicitly "apt-get purge" all package that we
intend to be removed.
This addresses the following two bugs:
* DLPX-64201 determine how to remove old linux kernels
* DLPX-78220 Old packages not removed after deferred upgrade
=> Don't use "apt-get autoremove" anymore

upgrade/upgrade-scripts/execute
We've discovered that "apt-get autoremove" does not work for our needs.
Specifically, packages may erroneously remain installed due to suggested
and recommended package dependencies, as well as due to virtual package
dependencies. While we could alleviate the issue w.r.t. suggested and
recommended dependencies via configuration changes, there isn't a clear
way to resolve the issue for virtual packages. Thus, the solution
adopted in this change is to simply not use "apt-get automoremove"
anymore, and instead, explicitly "apt-get purge" all package that we
intend to be removed.
This addresses the following two bugs:
* DLPX-64201 determine how to remove old linux kernels
* DLPX-78220 Old packages not removed after deferred upgrade
=> Don't use "apt-get autoremove" anymore (#642)

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
ab-pre-push: http://selfservice.jenkins.delphix.com/job/appliance-build/job/master/job/pre-push/28/
I cloned a VM from the dcol1 group from this build to test that the correct set of services were masked.
```
root@seb-dcenter-test:~# systemctl status named.service
● named.service
Loaded: masked (Reason: Unit named.service is masked.)
Active: inactive (dead)
root@seb-dcenter-test:~# systemctl status isc-dhcp-server.service
● isc-dhcp-server.service
Loaded: masked (Reason: Unit isc-dhcp-server.service is masked.)
Active: inactive (dead)
root@seb-dcenter-test:~# systemctl status isc-dhcp-server6.service
● isc-dhcp-server6.service
Loaded: masked (Reason: Unit isc-dhcp-server6.service is masked.)
Active: inactive (dead)
```
=> TOOL-12406 named.service may conflict with dcenter-dhcp.service on dcenter-internal variant

build.gradle, live-build/build.gradle, live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary, upgrade/upgrade-scripts/common.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
Adding minimum version property to root dataset
The minimum version property is used for
1. Upgrade: to determine minimum version needed for this image
2. Replication, FCR: minimum FCR version compatible
Test:
http://collins.d.delphix.com:20855/job/devops-gate/job/master/job/appliance-build/job/master/job/pre-push/29/console
Verified the upgrade image for the property.
New Job: http://collins.d.delphix.com:20855/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1/console
=> DLPX-77974 Add minimum version property to root dataset

live-build/auto/config, live-build/config/archives/delphix-secondary-mirror.list.in, live-build/config/archives/localhost.list, live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml, scripts/aptly-repo-from-debs.sh, scripts/aptly-repo-from-image-diff.sh, scripts/build-ancillary-repository.sh, scripts/run-live-build.sh, upgrade/upgrade-scripts/execute, upgrade/upgrade-scripts/upgrade-container
Note: this will only be integrated when transitioning 6.0/stage to Ubuntu 20.04.
This is a clean cherry-pick of https://github.com/delphix/appliance-build/pull/622 under the covers.
Here's a summary of the changes:
* Update live-build distribution from bionic to focal
* Update the distribution of our upgrade images from bionic to focal (note that I don't believe that the name we use there matters at all and that we could simply use "delphix" as the distribution, that said it's something to be tested out)
* Update the secondary mirrors distribution list
* Remove mentions of systemd-timesyncd.service since that service is not installed on 20.04
This code has been soaking on master for a few months.
=> TOOL-12418 [Backport of TOOL-12369 to 6.0.13.0] appliance-build: changes for Ubuntu 20.04

live-build/config/archives/delphix-secondary-mirror.list.in, live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
Clean cherry pick. 
Goes together with the app-gate change  http://reviews.delphix.com/r/77706/.
=> CP-7160 [Backport of CP-6676 to 6.0.13.0] appliance-build changes to simplify the fluentd build

upgrade/upgrade-scripts/common.sh
This is the second attempt to fix this issue.  
The failed fix integrated for DLPX-78736 rightly saw that td-agent needed to be masked in the fix_and_migrate_services() function in the upgrade script appliance-build/upgrad/upgrad-scripts/comm.sh.  However; the logic in that script does not work for new services.  It only masks existing services that are in the masked or disabled state.  
I added a separate lists of services that should always be masked after upgrade.   
Upgrade tests: http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/614/
=> DLPX-79367 td-agent service is not masked after upgrade

live-build/build.gradle, live-build/config/hooks/configuration/81-upgrade-repository.binary, scripts/run-live-build.sh
Current BOM doesn't contain the linux packages that are installed part of the OS. Also, there is no easy way to check the version of these packages without looking at the delphix engine.
While creating the delphix-entire package we aggregate the packages that need to be present for the install. We can sync this list to S3 and upload to download.delphix.com part of BOM. Other part of the review: http://reviews.delphix.com/r/79217/
Check the above review.
=> DLPX-80114 Add list of installed linux packages for each platform variant during appliance build

live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml, live-build/variants/internal-dcenter/package-lists/dcenter.list.chroot, scripts/run-live-build.sh
This reverts commit 0d0cf2cee47ea192cd6f7f4c2e7d904654724c55. This commit is causing https://delphix.atlassian.net/browse/DLPX-80624.
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/1491/
=> Revert "DLPX-80424 [Backport of DLPX-80287 to 6.0.14.0] remove unnecessary "recommended" packages from appliance (#670)"

live-build/config/archives/delphix-secondary-mirror.list.in
This PR add the `stable` ppa so that we can add `telegraf` into the delphix image.
=> TOOL-13469 appliance-build changes to add telegraf support

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
iSCSI Initiator QA tests need `nmap`.
Add `nmap` to the list of packages in the qa-internal Ansible rules.
```
$ git ab-pre-push
Your build is at: http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/2113/
```
Build passed with 100% success.
Then, I did a quick manual inspection of my built appliance:
```
$ which nmap
/usr/bin/nmap
$ dpkg-query --search /usr/bin/nmap
nmap: /usr/bin/nmap
$ dpkg-query --status nmap
Package: nmap
Status: install ok installed
...
```
Changes look good.
=> QA-35550 Add nmap to qa-internal appliance builds

live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
This is a `git merge` of `master` into `6.0/stage`; this is in preparation for development to be done directly on `6.0/stage` instead of `master`.
Here's the only difference that exists between `6.0/stage` and `master` after this change:
```
± git diff HEAD..origin/master
diff --git a/branch.config b/branch.config
index 9e572e6..cedb298 100644
--- a/branch.config
+++ b/branch.config
@@ -10,4 +10,4 @@
#
-UPSTREAM_BRANCH="6.0/stage"
+UPSTREAM_BRANCH="master"
```
Additionally, here are the git conflicts that arose during the merge, and how they were addressed:
```
± git show
commit f7ab804d752e05d5ef157ada08a0ca318c1a1583 (HEAD -> 6.0/stage, ps/6.0/stage)
Author: Prakash Surya <prakash.surya@delphix.com>
Date:   Tue Jul 19 09:56:52 2022 -0700
fixup: fix git conflicts
diff --git …
```
=> GHM-743 transition more platform repository to pre-gitflow branching model

live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
Scale setup creation fails trying to install the `filebeat` agent with the below error as it tries to install the `gnupg` package first as its dependency (the installation of `filebeat` agent needs to add GPG keys which is done by `sudo apt-key add` command which in turn requires `gnupg` package installation).
```
11:51:08  Package gnupg is not available, but is referred to by another package.
11:51:08  This may mean that the package is missing, has been obsoleted, or
11:51:08  is only available from another source
11:51:08  
11:51:08  E: Package 'gnupg' has no installation candidate
```
Adding `gnupg` as QA image requirements as filebeat agent is extensively used in the Scalability testing for automated monitoring of the engine's logs.
Able to add GPG keys after manually installing the …
=> SCAL-738 Setup creation fails trying to install filebeat agent on dlpx-qa images as gnupg installation fails

live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary
Exporting the rpool that is being installed by appliance-build
sometimes fails with EBUSY.
While we don't have a root-cause for the EBUSY failure, this fix attempts to
workaround it. The umount step that is done immediately before the export also
previously failed with EBUSY, but a retry loop was added to that step which
proved to be a viable workaround. The same approach is attempted here with the
export step.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3641/
=> TOOL-11972 appliance-build on focal: cannot export 'rpool': pool is busy

live-build/misc/ansible-roles/appliance-build.buildserver-internal/tasks/main.yml, live-build/variants/internal-buildserver/ansible/playbook.yml, live-build/variants/internal-buildserver/ansible/roles
This change adds a new "buildserver" variant, where the intention is to use this variant for building our software (packages, appliance, etc), rather than our current buildserver image which is based on Ubuntu.
=> TOOL-16451 Add new "buildserver" variant

live-build/config/hooks/vm-artifacts/90-raw-disk-image.binary
Our current Ubuntu buildservers have 256G of root disk space, so I'm changing the delphix buildserver to match. Otherwise, we hit ENOSPC issues when running appliance-build, (I think) due to the size of the VM and upgrade artifacts.
=> TOOL-16510 Add more rpool space for buildserver variant
