- scripts/run-live-build.sh
To test this change I:
1. cloned the bootstrap-18-04 vm
2. cloned this repo
3. applied my diff
4. ran the live build with my JENKINSID and GITBRANCH set
> Modify run-live-build to default to new linux buckets

- README.md
- live-build/base/config/package-lists/minimal.list.chroot
- live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
- live-build/misc/ansible-roles/appliance-build.delphix-ldap/files/etc/idmapd.conf
- live-build/misc/ansible-roles/appliance-build.delphix-ldap/files/etc/ldap.conf
- live-build/misc/ansible-roles/appliance-build.delphix-ldap/files/etc/ldap/ldap.conf
- live-build/misc/ansible-roles/appliance-build.delphix-ldap/tasks/main.yml
- live-build/variants/internal-dcenter/ansible/playbook.yml
- live-build/variants/internal-dcenter/ansible/roles
- live-build/variants/internal-dcenter/config/hooks
- scripts/create-variant.sh
This adds a new dcenter variant that is based off the internal-dev variant.
> LX-1092 create dcenter build variant

- live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
Please see the individual commit messages for more details.
> Restore default value for a couple ZFS parameters

- live-build/misc/live-build-hooks/81-upgrade-repository.binary
- live-build/misc/live-build-hooks/template.ctl
This PR changes delphix-entire's package version to be the same as delphix-virtualization's version
Goes hand-in-hand with http://reviews.delphix.com/r/43634
> LX-1414 Build delphix-virtualization/entire with x.x.x.x scheme

- live-build/misc/live-build-hooks/82-upgrade-repository.binary
- live-build/misc/live-build-hooks/template.ctl
This reverts commit d581766404562cc987338b89749c6a3862d8a182.
> Revert "LX-1414 Build delphix-virtualization/entire with x.x.x.x scheme"

- live-build/misc/live-build-hooks/91-gce-machine-image.binary
- scripts/run-live-build.sh
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/174/
> LX-1571 need raw image artifact for GCP

- live-build/misc/live-build-hooks/90-raw-disk-image.binary
> Use "--make-rslave" in 90-raw-disk-image.binary

- live-build/misc/live-build-hooks/90-raw-disk-image.binary
- live-build/misc/upgrade-scripts/upgrade-container
This reverts commit 30f82a36ebdb7c1531f69ead0641ddc9a0b0b3f9.
> Revert "Use a dedicated dataset for GRUB configuration"

- scripts/fetch-livebuild-artifacts.sh
When we build an upgrade image for a variant, we currently download all
of the artfacts produced by live build for that variant. We really only
need the .deb.tar.gz files though. By omitting the other files, we can
save time and disk space.
> Only download .debs.tar.gz when building upgrade image

- live-build/config/hooks/90-raw-disk-image.binary
This reverts commit e128e44ed19d988ede8b953e651ae464cbf6236a.
> Revert "Rely on delphix-platfrom to create crashdump dataset"

- live-build/misc/ansible-roles/appliance-build.zfsonlinux-development/tasks/main.yml
> Add "mandoc" and "flake8" packages for ZFS development

- live-build/build.gradle
- live-build/config/hooks/82-upgrade-repository.binary
- scripts/docker-run.sh
See app-gate review for full architecture explanation http://reviews.delphix.com/r/46631/
Jenkins changes here http://reviews.delphix.com/r/46521/
> LX-1682 De-couple delphix-entire and delphix-virtualization version

- scripts/build-ancillary-repository.sh
Following the integration of https://github.com/delphix/linux-pkg/pull/21, we can now remove the build of Java8 from here.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/654/
> Java is now built by Linux-pkg

- live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
This reverts commit 02554d6cd20c9b089645d0b0928f824778f31313.
Closes #255
> Revert "Add openjdk to the dcenter build."

- upgrade/upgrade-scripts/upgrade-container
Ensured that this PR running together with its respective appstack bits doesn't hit any issues.
Link: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1202/flowGraphTable/
(^ on the above link dx-test hit an unrelated issue see respective review of appstack changes for more info)
> 294 - add new netplan file to copy-on-upgrade list

- live-build/misc/migration-scripts/dx_upg_stress_options
See related work for more details:
app-gate: http://reviews.delphix.com/r/52562
delphix-platform: https://github.com/delphix/delphix-platform/pull/138
> add new app-gate stress options

- live-build/misc/migration-scripts/dx_apply
- live-build/misc/migration-scripts/dx_execute
- live-build/misc/migration-scripts/dx_upg_stress_options
- live-build/misc/migration-scripts/dx_verify
Backport of https://github.com/delphix/appliance-build/pull/387
> DLPX-66697 [Backport of Issue DLPX-66696 to 6.0.0.0] migration: add stress options in the pre-reboot dx scripts

- upgrade/upgrade-scripts/upgrade-container
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3010/
> DLPX-68825 delphix-fluentd service disabled after not-in-place upgrade

- upgrade/upgrade-scripts/upgrade-container
> DLPX-68826 [Backport of DLPX-68825 to 6.0.2.0] delphix-fluentd service disabled after not-in-place upgrade

- upgrade/upgrade-scripts/common.sh
- upgrade/upgrade-scripts/rootfs-container
- upgrade/upgrade-scripts/upgrade
JIRA link for Backport: https://jira.delphix.com/browse/DLPX-69176
Clean cherry-picks of:
- #413 
- #448 
- #449 
- #445 
----------------------------
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3154/
> Backports of 4 commits to add 'upgrade finalize' to 6.0/stage

- upgrade/upgrade-scripts/upgrade-container
This is a clean cherry-pick of #467
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3634/
> copy static DNS configuration for not-in-place upgrades

- live-build/misc/ansible-roles/appliance-build.recovery-environment/meta/main.yml
- live-build/misc/ansible-roles/appliance-build.recovery-environment/tasks/main.yml
- live-build/variants/external-standard/ansible/playbook.yml
- live-build/variants/internal-dev/ansible/playbook.yml
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3872/ (in progress)
> Backport: Install recovery env

- live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
This is a backport of installing snmptrapd package to dev build.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/dx-integration-tests/22326/parameters/
I cloned the VM from the snapshot and found the snmptrapd library installed.
snmptrapd package was not available.
Issue Number: N/A
- Added snmptrapd package that will be available in the 6.0 stage build. This is needed for setting up SNMP managers to test SNMP traps and informs.
-
-
> QA-25826 [Backport of QA-20893] Add the snmptrapd pkg to the delphix VM

- live-build/config/hooks/vm-artifacts/template.ovf
This is a clean cherry-pick of https://github.com/delphix/appliance-build/pull/506
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4523/ (in progress)
> Backport hot-add to 6.0.6.0

- live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
Removing no-longer-used Python 2 packages and adding two new libraries I am using in a forthcoming change.
> Python package updates

- build.gradle
- upgrade/README.md
- upgrade/upgrade-scripts/rootfs-cleanup
- upgrade/upgrade-scripts/upgrade
> DLPX-75347 old rootfs versions are not removed on upgrade in 6.0.8.0

- upgrade/upgrade-scripts/execute
This reverts commit be1ecc9701ca18b05dec0ec6b6016bb39bc79b6c.
> Revert "DLPX-64201 determine how to remove old linux kernels (#548)"

- upgrade/upgrade-scripts/execute
This reverts commit f6421aa1f2112ec17eb53737d079ff87f1e1a533.
> Revert "DLPX-68959 [Backport of DLPX-64201 to 6.0.9.0] determine how to remove old linux kernels (#549)"

- live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
Clean cherry-pick of: https://github.com/delphix/appliance-build/pull/557
See PR above for context, problem, and solution.
> CP-5356 [Backport of CP-5334 to 6.0.9.0] Add ufw package to appliance-build

- build.gradle
- live-build/config/hooks/configuration/81-upgrade-repository.binary
- live-build/config/hooks/configuration/template.ctl
- scripts/create-build-info-package.sh
> DLPX-76293 Copy Hotfix Metadata Generation to appliance-build (#574)

- live-build/misc/ansible-roles/appliance-build.virtualization-development/tasks/main.yml
Clean cherry-pick of https://github.com/delphix/appliance-build/pull/607
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6103/
> CP-5971 [Backport of CP-5946 to 6.0.11.0] Enable Java debug mode for sso app

- live-build/misc/ansible-roles/appliance-build.qa-internal/tasks/main.yml
Forward port of https://github.com/delphix/appliance-build/pull/636/, as requested by Prakash on that PR
[ab-pre-push](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3/) - PASSED
> Dlpx 78603

- live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
- live-build/variants/internal-dcenter/package-lists/dcenter.list.chroot
- scripts/run-live-build.sh
Clean cherry-pick #666 and #668.
This is dependent on both: https://github.com/delphix/delphix-platform/pull/368 and http://reviews.delphix.com/r/80284/
> DLPX-80424 [Backport of DLPX-80287 to 6.0.14.0] remove unnecessary "recommended" packages from appliance

- live-build/config/hooks/configuration/81-upgrade-repository.binary
> DLPX-79030 [Backport of DLPX-78464 to 6.0.14.0] Regression in appliance-build from DLPX-76293

- live-build/build.gradle
- live-build/config/hooks/configuration/81-upgrade-repository.binary
- scripts/run-live-build.sh
Clean cherrypick of: https://www.github.com/delphix/appliance-build/pull/663
> DLPX-80654 [Backport of DLPX-80114 to 6.0.14.0] Add list of installed linux packages for each platform variant during appliance build (#663)

- live-build/config/archives/delphix-secondary-mirror.list.in
> TOOL-13514 [Backport of TOOL-13469 to 6.0.14.0] appliance-build changes to add telegraf support

- live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
> CP-8412 [Backport of CP-8404 to 6.0.15.0] disable default telegraf service

- live-build/misc/ansible-roles/appliance-build.buildserver-internal/tasks/main.yml
- live-build/misc/ansible-roles/appliance-build.minimal-common/tasks/main.yml
This depends on: https://www.github.com/delphix/delphix-platform/pull/396
> TOOL-16594 Don't remove delphix user from existing groups
